/* Generated by wbuild from "Common.w"
** (generator version $Revision: 404 $ of $Date: 1999-09-28 09:56:30 -0600 (Tue, 28 Sep 1999) $)
*/
#include <X11/IntrinsicP.h>
#include <X11/StringDefs.h>
#line 1116 "Common.w"
#include <stdio.h>
#line 1117 "Common.w"
#include <assert.h>
#line 1118 "Common.w"
#include <X11/Xmu/Converters.h>
#line 1119 "Common.w"
#include "Converters.h"
#line 1120 "Common.w"
#include <X11/ShellP.h>
#include "CommonP.h"
#define focus_detail(detail) (detail ==NotifyAncestor ?"NotifyAncestor":detail ==NotifyVirtual ?"NotifyVirtual":detail ==NotifyInferior ?"NotifyInferior":detail ==NotifyNonlinear ?"NotifyNonlinear":detail ==NotifyNonlinearVirtual ?"NotifyNonlinearVirtual":detail ==NotifyPointer ?"NotifyPointer":detail ==NotifyPointerRoot ?"NotifyPointerRoot":detail ==NotifyDetailNone ?"NotifyDetailNone":"???")


#line 989 "Common.w"
static void focusIn(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 1010 "Common.w"
static void focusOut(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 1026 "Common.w"
static void traverseDown(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 1035 "Common.w"
static void traverseUp(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 1044 "Common.w"
static void traverseLeft(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 1053 "Common.w"
static void traverseRight(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 1065 "Common.w"
static void traverseNext(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 1074 "Common.w"
static void traversePrev(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 1085 "Common.w"
static void traverseNextTop(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 1094 "Common.w"
static void traverseHome(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 1104 "Common.w"
static void traverseCurrent(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);

static XtActionsRec actionsList[] = {
{"focusIn", focusIn},
{"focusOut", focusOut},
{"traverseDown", traverseDown},
{"traverseUp", traverseUp},
{"traverseLeft", traverseLeft},
{"traverseRight", traverseRight},
{"traverseNext", traverseNext},
{"traversePrev", traversePrev},
{"traverseNextTop", traverseNextTop},
{"traverseHome", traverseHome},
{"traverseCurrent", traverseCurrent},
};
static void _resolve_inheritance(
#if NeedFunctionPrototypes
WidgetClass
#endif
);
#line 259 "Common.w"
static void class_initialize(
#if NeedFunctionPrototypes
void
#endif
);
#line 306 "Common.w"
static void initialize(
#if NeedFunctionPrototypes
Widget ,Widget,ArgList ,Cardinal *
#endif
);
#line 339 "Common.w"
static Boolean  set_values(
#if NeedFunctionPrototypes
Widget ,Widget ,Widget,ArgList ,Cardinal *
#endif
);
#line 391 "Common.w"
static void compute_inside(
#if NeedFunctionPrototypes
Widget,Position *,Position *,Dimension *,Dimension *
#endif
);
#line 403 "Common.w"
static Dimension  total_frame_width(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 410 "Common.w"
static void expose(
#if NeedFunctionPrototypes
Widget,XEvent *,Region 
#endif
);
#line 422 "Common.w"
static void destroy(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 435 "Common.w"
static void realize(
#if NeedFunctionPrototypes
Widget,XtValueMask *,XSetWindowAttributes *
#endif
);
#line 451 "Common.w"
static void highlight_border(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 480 "Common.w"
static void unhighlight_border(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 505 "Common.w"
static Boolean  accept_focus(
#if NeedFunctionPrototypes
Widget,Time *
#endif
);
#line 529 "Common.w"
static Boolean  would_accept_focus(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 640 "Common.w"
static void traverse(
#if NeedFunctionPrototypes
Widget,TraversalDirection ,Widget ,Time *
#endif
);
#line 937 "Common.w"
static Boolean  lighter_color(
#if NeedFunctionPrototypes
Widget,Pixel ,Pixel *
#endif
);
#line 953 "Common.w"
static Boolean  darker_color(
#if NeedFunctionPrototypes
Widget,Pixel ,Pixel *
#endif
);
#line 676 "Common.w"
#define done(type, value) do {\
	if (to->addr != NULL) {\
	    if (to->size < sizeof(type)) {\
	        to->size = sizeof(type);\
	        return False;\
	    }\
	    *(type*)(to->addr) = (value);\
        } else {\
	    static type static_val;\
	    static_val = (value);\
	    to->addr = (XtPointer)&static_val;\
        }\
        to->size = sizeof(type);\
        return True;\
    }while (0 )


#line 693 "Common.w"
static Boolean  cvtStringToAlignment(
#if NeedFunctionPrototypes
Display *,XrmValuePtr ,Cardinal *,XrmValuePtr ,XrmValuePtr ,XtPointer *
#endif
);
#line 729 "Common.w"
static Boolean  cvtAlignmentToString(
#if NeedFunctionPrototypes
Display *,XrmValuePtr ,Cardinal *,XrmValuePtr ,XrmValuePtr ,XtPointer *
#endif
);
#line 759 "Common.w"
static char  extraTranslations[] = "\
	<FocusIn>: focusIn()\n\
	<FocusOut>: focusOut()\n\
	<Key>Up: traverseUp()\n\
	<Key>Down: traverseDown()\n\
	<Key>Left: traverseLeft()\n\
	<Key>Right: traverseRight()\n\
	<Key>Next: traverseNext()\n\
	~Shift<Key>Tab: traverseNext()\n\
	<Key>Prior: traversePrev()\n\
	Shift<Key>Tab: traversePrev()\n\
	<Key>KP_Enter: traverseNextTop()\n\
	<Key>Home: traverseHome()";
#line 777 "Common.w"
static void create_bordergc(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 804 "Common.w"
static Boolean  traverse_to_direction(
#if NeedFunctionPrototypes
Widget,TraversalDirection ,int ,int ,Widget *,int *
#endif
);
#line 852 "Common.w"
static void traverse_to_next(
#if NeedFunctionPrototypes
Widget,Widget ,Time *
#endif
);
#line 869 "Common.w"
static void traverse_to_prev(
#if NeedFunctionPrototypes
Widget,Widget ,Time *
#endif
);
#line 882 "Common.w"
static void traverse_to_next_top(
#if NeedFunctionPrototypes
Widget,Widget ,Time *
#endif
);
#line 898 "Common.w"
static void create_xcc(
#if NeedFunctionPrototypes
Widget,int ,XrmValue *
#endif
);
#line 693 "Common.w"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 693 "Common.w"
static Boolean  cvtStringToAlignment(Display * display,XrmValuePtr  args,Cardinal * num_args,XrmValuePtr  from,XrmValuePtr  to,XtPointer * converter_data)
#else
#line 693 "Common.w"
static Boolean  cvtStringToAlignment(display,args,num_args,from,to,converter_data)Display * display;XrmValuePtr  args;Cardinal * num_args;XrmValuePtr  from;XrmValuePtr  to;XtPointer * converter_data;
#endif
#line 694 "Common.w"
{
    Alignment a = 0;
    char c, *t, *s = (char*) from->addr;

    if (*num_args != 0)
	XtAppErrorMsg(XtDisplayToApplicationContext(display),
		      "cvtStringToAlignment", "wrongParameters",
		      "XtToolkitError",
		      "String to Alignment conversion needs no arguments",
		      (String*) NULL, (Cardinal*) NULL);

    while (*s) {
	for (; isspace(*s); s++) ;
	for (t = s; *t && ! isspace(*t); t++) ;
	c = *t;
	*t = '\0';
	if (XmuCompareISOLatin1(s, "top") == 0) a |= XfwfTop;
	else if (XmuCompareISOLatin1(s, "bottom") == 0) a |= XfwfBottom;
	else if (XmuCompareISOLatin1(s, "center") == 0) ; /* skip */
	else if (XmuCompareISOLatin1(s, "left") == 0) a |= XfwfLeft;
	else if (XmuCompareISOLatin1(s, "right") == 0) a |= XfwfRight;
	else {
	    XtDisplayStringConversionWarning(display, (char*) from->addr, 
					     "Alignment");
	    break;
	}
	*t = c;
	s = t;
    }
    done(Alignment, a);
    /* NOTREACHED */
}
#line 729 "Common.w"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 729 "Common.w"
static Boolean  cvtAlignmentToString(Display * display,XrmValuePtr  args,Cardinal * num_args,XrmValuePtr  from,XrmValuePtr  to,XtPointer * converter_data)
#else
#line 729 "Common.w"
static Boolean  cvtAlignmentToString(display,args,num_args,from,to,converter_data)Display * display;XrmValuePtr  args;Cardinal * num_args;XrmValuePtr  from;XrmValuePtr  to;XtPointer * converter_data;
#endif
#line 730 "Common.w"
{
    Alignment *a = (Alignment*) from->addr;

    if (*num_args != 0)
	XtAppErrorMsg(XtDisplayToApplicationContext(display),
		      "cvtAlignmentToString", "wrongParameters",
		      "XtToolkitError",
		      "Alignment to String conversion needs no arguments",
		      (String*) NULL, (Cardinal*) NULL);
    switch (*a) {
    case XfwfCenter: done(String, "center");
    case XfwfBottom: done(String, "bottom");
    case XfwfTop: done(String, "top");
    case XfwfLeft: done(String, "left");
    case XfwfRight: done(String, "right");
    case XfwfBottom + XfwfLeft: done(String, "bottom left");
    case XfwfBottom + XfwfRight: done(String, "bottom right");
    case XfwfTop + XfwfLeft: done(String, "top left");
    case XfwfTop + XfwfRight: done(String, "top right");
    default: done(String, "unknown");
    }
    /* NOTREACHED */
}
#line 777 "Common.w"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 777 "Common.w"
static void create_bordergc(Widget self)
#else
#line 777 "Common.w"
static void create_bordergc(self)Widget self;
#endif
#line 778 "Common.w"
{
    XtGCMask mask;
    XGCValues values;

    if (((XfwfCommonWidget)self)->xfwfCommon.bordergc) XtReleaseGC(self, ((XfwfCommonWidget)self)->xfwfCommon.bordergc);
    if (((XfwfCommonWidget)self)->xfwfCommon.highlightPixmap != None) {
	mask = GCFillStyle | GCTile;
	values.fill_style = FillTiled;
	values.tile = ((XfwfCommonWidget)self)->xfwfCommon.highlightPixmap;
    } else {
	mask = GCFillStyle | GCForeground;
	values.fill_style = FillSolid;
	values.foreground = ((XfwfCommonWidget)self)->xfwfCommon.highlightColor;
    }
    ((XfwfCommonWidget)self)->xfwfCommon.bordergc = XtGetGC(self, mask, &values);
}
#line 804 "Common.w"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 804 "Common.w"
static Boolean  traverse_to_direction(Widget self,TraversalDirection  dir,int  x,int  y,Widget * found,int * distance)
#else
#line 804 "Common.w"
static Boolean  traverse_to_direction(self,dir,x,y,found,distance)Widget self;TraversalDirection  dir;int  x;int  y;Widget * found;int * distance;
#endif
#line 805 "Common.w"
{
    int i;
    Position rx, ry;
    int dist;
    Boolean found_child = False;

    if (! ((XfwfCommonWidget)self)->xfwfCommon.traversalOn) return False;
    /*
     * First recurse to all descendants
     */
    for (i = 0; i < ((XfwfCommonWidget)self)->composite.num_children; i++)
        if (XtIsSubclass(((XfwfCommonWidget)self)->composite.children[i], xfwfCommonWidgetClass)
            && traverse_to_direction(((XfwfCommonWidget)self)->composite.children[i], dir, x, y, found, distance))
            found_child = True;
    if (found_child) return True;
    /*
     * No child found, now check own position and distance
     */
    switch (dir) {
    case TraverseHome: rx = 0; ry = 0; break;
    case TraverseLeft: rx = ((XfwfCommonWidget)self)->core.width; ry = ((XfwfCommonWidget)self)->core.height/2; break;
    case TraverseDown: rx = ((XfwfCommonWidget)self)->core.width/2; ry = 0; break;
    case TraverseRight: rx = 0; ry = ((XfwfCommonWidget)self)->core.height/2; break;
    case TraverseUp: rx = ((XfwfCommonWidget)self)->core.width/2; ry = ((XfwfCommonWidget)self)->core.height; break;
    }
    XtTranslateCoords(self, rx, ry, &rx, &ry);
    if ((dir == TraverseUp && ry > y)
        || (dir == TraverseLeft && rx > x)
        || (dir == TraverseDown && ry < y)
        || (dir == TraverseRight && rx < x)) return False;
    dist = (rx - x)*(rx - x) + (ry - y)*(ry - y);
    if (dist >= *distance) return False;
    /*
     * We are the best so far, but do we want the focus?
     */
    if (! ((XfwfCommonWidgetClass)self->core.widget_class)->xfwfCommon_class.would_accept_focus(self)) return False;
    *distance = dist;
    *found = self;
    return True;
}
#line 852 "Common.w"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 852 "Common.w"
static void traverse_to_next(Widget self,Widget  current,Time * time)
#else
#line 852 "Common.w"
static void traverse_to_next(self,current,time)Widget self;Widget  current;Time * time;
#endif
#line 853 "Common.w"
{
    int i = 0;
    Widget parent = XtParent(self);

    while (i < ((XfwfCommonWidget)self)->composite.num_children && ((XfwfCommonWidget)self)->composite.children[i] != current) i++;
    for (i++; i < ((XfwfCommonWidget)self)->composite.num_children; i++)
        if (XtCallAcceptFocus(((XfwfCommonWidget)self)->composite.children[i], time)) return;
    if (XtIsSubclass(parent, xfwfCommonWidgetClass))
        ((XfwfCommonWidgetClass)parent->core.widget_class)->xfwfCommon_class.traverse(parent, TraverseNext, self, time);
}
#line 869 "Common.w"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 869 "Common.w"
static void traverse_to_prev(Widget self,Widget  current,Time * time)
#else
#line 869 "Common.w"
static void traverse_to_prev(self,current,time)Widget self;Widget  current;Time * time;
#endif
#line 870 "Common.w"
{
    int i = 0;
    Widget parent = XtParent(self);

    while (i < ((XfwfCommonWidget)self)->composite.num_children && ((XfwfCommonWidget)self)->composite.children[i] != current) i++;
    for (i--; i >= 0; i--)
        if (XtCallAcceptFocus(((XfwfCommonWidget)self)->composite.children[i], time)) return;
    if (XtIsSubclass(parent, xfwfCommonWidgetClass))
        ((XfwfCommonWidgetClass)parent->core.widget_class)->xfwfCommon_class.traverse(parent, TraversePrev, self, time);
}
#line 882 "Common.w"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 882 "Common.w"
static void traverse_to_next_top(Widget self,Widget  current,Time * time)
#else
#line 882 "Common.w"
static void traverse_to_next_top(self,current,time)Widget self;Widget  current;Time * time;
#endif
#line 883 "Common.w"
{
    Widget parent = XtParent(self);

    if (XtIsSubclass(parent, xfwfCommonWidgetClass))
	((XfwfCommonWidgetClass)parent->core.widget_class)->xfwfCommon_class.traverse(parent, TraverseNextTop, current, time);
    else
	XtCallCallbackList(self, ((XfwfCommonWidget)self)->xfwfCommon.nextTop, NULL);
}
#line 898 "Common.w"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 898 "Common.w"
static void create_xcc(Widget self,int  offset,XrmValue * value)
#else
#line 898 "Common.w"
static void create_xcc(self,offset,value)Widget self;int  offset;XrmValue * value;
#endif
#line 899 "Common.w"
{
    Visual *visual;
    Widget w;
    static XCC xcc;

    if (! ((XfwfCommonWidget)self)->xfwfCommon.useXCC) {
        xcc = NULL;
        ((XfwfCommonWidget)self)->xfwfCommon.own_xcc = FALSE;
    } else {
        for (w = XtParent(self); w; w = XtParent(w)) {
            if (XtIsSubclass(w, xfwfCommonWidgetClass)) {
                xcc = ((XfwfCommonWidget)w)->xfwfCommon.xcc;
                ((XfwfCommonWidget)self)->xfwfCommon.own_xcc = FALSE;
                break;
            } else if (XtIsShell(w)) {
                if (((ShellWidget)w)->shell.visual)
                    visual = ((ShellWidget)w)->shell.visual;
                else
                    visual = DefaultVisualOfScreen(XtScreen(self));
                xcc = XCCCreate
                    (XtDisplay(self), visual, ((XfwfCommonWidget)self)->xfwfCommon.usePrivateColormap,
                     ((XfwfCommonWidget)self)->xfwfCommon.useStandardColormaps, ((XfwfCommonWidget)self)->xfwfCommon.standardColormap,
                     &((XfwfCommonWidget)self)->core.colormap);
                ((XfwfCommonWidget)self)->xfwfCommon.own_xcc = TRUE;
                break;
            }
        }
    }
    value->addr = (XtPointer) &xcc;    
}

static XtResource resources[] = {
#line 109 "Common.w"
{XtNuseXCC,XtCUseXCC,XtRBoolean,sizeof(((XfwfCommonRec*)NULL)->xfwfCommon.useXCC),XtOffsetOf(XfwfCommonRec,xfwfCommon.useXCC),XtRImmediate,(XtPointer)TRUE },
#line 117 "Common.w"
{XtNusePrivateColormap,XtCUsePrivateColormap,XtRBoolean,sizeof(((XfwfCommonRec*)NULL)->xfwfCommon.usePrivateColormap),XtOffsetOf(XfwfCommonRec,xfwfCommon.usePrivateColormap),XtRImmediate,(XtPointer)FALSE },
#line 126 "Common.w"
{XtNuseStandardColormaps,XtCUseStandardColormaps,XtRBoolean,sizeof(((XfwfCommonRec*)NULL)->xfwfCommon.useStandardColormaps),XtOffsetOf(XfwfCommonRec,xfwfCommon.useStandardColormaps),XtRImmediate,(XtPointer)TRUE },
#line 135 "Common.w"
{XtNstandardColormap,XtCStandardColormap,XtRAtom,sizeof(((XfwfCommonRec*)NULL)->xfwfCommon.standardColormap),XtOffsetOf(XfwfCommonRec,xfwfCommon.standardColormap),XtRImmediate,(XtPointer)0 },
#line 142 "Common.w"
{XtNxcc,XtCXCc,XtRXCC,sizeof(((XfwfCommonRec*)NULL)->xfwfCommon.xcc),XtOffsetOf(XfwfCommonRec,xfwfCommon.xcc),XtRCallProc,(XtPointer)create_xcc },
#line 149 "Common.w"
{XtNtraversalOn,XtCTraversalOn,XtRBoolean,sizeof(((XfwfCommonRec*)NULL)->xfwfCommon.traversalOn),XtOffsetOf(XfwfCommonRec,xfwfCommon.traversalOn),XtRImmediate,(XtPointer)True },
#line 157 "Common.w"
{XtNhighlightThickness,XtCHighlightThickness,XtRDimension,sizeof(((XfwfCommonRec*)NULL)->xfwfCommon.highlightThickness),XtOffsetOf(XfwfCommonRec,xfwfCommon.highlightThickness),XtRImmediate,(XtPointer)2 },
#line 165 "Common.w"
{XtNhighlightColor,XtCHighlightColor,XtRColor,sizeof(((XfwfCommonRec*)NULL)->xfwfCommon.highlightColor),XtOffsetOf(XfwfCommonRec,xfwfCommon.highlightColor),XtRString,(XtPointer)XtDefaultForeground },
#line 173 "Common.w"
{XtNbackground,XtCBackground,XtRColor,sizeof(((XfwfCommonRec*)NULL)->xfwfCommon.background),XtOffsetOf(XfwfCommonRec,xfwfCommon.background),XtRString,(XtPointer)XtDefaultBackground },
#line 180 "Common.w"
{XtNhighlightPixmap,XtCHighlightPixmap,XtRPixmap,sizeof(((XfwfCommonRec*)NULL)->xfwfCommon.highlightPixmap),XtOffsetOf(XfwfCommonRec,xfwfCommon.highlightPixmap),XtRImmediate,(XtPointer)None },
#line 190 "Common.w"
{XtNnextTop,XtCNextTop,XtRCallback,sizeof(((XfwfCommonRec*)NULL)->xfwfCommon.nextTop),XtOffsetOf(XfwfCommonRec,xfwfCommon.nextTop),XtRImmediate,(XtPointer)NULL },
#line 196 "Common.w"
{XtNuserData,XtCUserData,XtRPointer,sizeof(((XfwfCommonRec*)NULL)->xfwfCommon.userData),XtOffsetOf(XfwfCommonRec,xfwfCommon.userData),XtRImmediate,(XtPointer)NULL },
};

XfwfCommonClassRec xfwfCommonClassRec = {
{ /* core_class part */
/* superclass   	*/  (WidgetClass) &compositeClassRec,
/* class_name   	*/  "XfwfCommon",
/* widget_size  	*/  sizeof(XfwfCommonRec),
/* class_initialize 	*/  class_initialize,
/* class_part_initialize*/  _resolve_inheritance,
/* class_inited 	*/  FALSE,
/* initialize   	*/  initialize,
/* initialize_hook 	*/  NULL,
/* realize      	*/  realize,
/* actions      	*/  actionsList,
/* num_actions  	*/  11,
/* resources    	*/  resources,
/* num_resources 	*/  12,
/* xrm_class    	*/  NULLQUARK,
/* compres_motion 	*/  True ,
/* compress_exposure 	*/  XtExposeCompressMultiple ,
/* compress_enterleave 	*/  True ,
/* visible_interest 	*/  TRUE ,
/* destroy      	*/  destroy,
/* resize       	*/  XtInheritResize,
/* expose       	*/  expose,
/* set_values   	*/  set_values,
/* set_values_hook 	*/  NULL,
/* set_values_almost 	*/  XtInheritSetValuesAlmost,
/* get_values+hook 	*/  NULL,
/* accept_focus 	*/  accept_focus,
/* version      	*/  XtVersion,
/* callback_private 	*/  NULL,
/* tm_table      	*/  NULL,
/* query_geometry 	*/  XtInheritQueryGeometry,
/* display_acceleator 	*/  XtInheritDisplayAccelerator,
/* extension    	*/  NULL 
},
{ /* composite_class part */
XtInheritGeometryManager,
XtInheritChangeManaged,
XtInheritInsertChild,
XtInheritDeleteChild,
NULL
},
{ /* XfwfCommon_class part */
compute_inside,
total_frame_width,
highlight_border,
unhighlight_border,
would_accept_focus,
traverse,
lighter_color,
darker_color,
/* traversal_trans */  NULL ,
},
};
WidgetClass xfwfCommonWidgetClass = (WidgetClass) &xfwfCommonClassRec;
/*ARGSUSED*/
#line 989 "Common.w"
static void focusIn(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    Time time = CurrentTime;

    if (event->type != FocusIn)
	XtError("focusIn action may only be bound to FocusIn events");
    if (! ((XfwfCommonWidget)self)->xfwfCommon.traversalOn)
	return;
    if (event->xfocus.detail == NotifyAncestor
	|| event->xfocus.detail == NotifyInferior
	|| event->xfocus.detail == NotifyNonlinear) {
	if (! ((XfwfCommonWidget)self)->xfwfCommon.traversal_focus) (void) ((XfwfCommonWidgetClass)self->core.widget_class)->core_class.accept_focus(self, &time);
    } else if (((XfwfCommonWidget)self)->xfwfCommon.traversal_focus) {
	((XfwfCommonWidgetClass)self->core.widget_class)->xfwfCommon_class.unhighlight_border(self);
	((XfwfCommonWidget)self)->xfwfCommon.traversal_focus = False;
    }
}

/*ARGSUSED*/
#line 1010 "Common.w"
static void focusOut(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    if (event->type != FocusOut)
	XtError("focusOut action may only be bound to FocusOut events");
    if (((XfwfCommonWidget)self)->xfwfCommon.traversal_focus) {
	((XfwfCommonWidgetClass)self->core.widget_class)->xfwfCommon_class.unhighlight_border(self);
	((XfwfCommonWidget)self)->xfwfCommon.traversal_focus = False;
    }
}

/*ARGSUSED*/
#line 1026 "Common.w"
static void traverseDown(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    ((XfwfCommonWidgetClass)self->core.widget_class)->xfwfCommon_class.traverse(self, TraverseDown, self, &event->xkey.time);
}

/*ARGSUSED*/
#line 1035 "Common.w"
static void traverseUp(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    ((XfwfCommonWidgetClass)self->core.widget_class)->xfwfCommon_class.traverse(self, TraverseUp, self, &event->xkey.time);
}

/*ARGSUSED*/
#line 1044 "Common.w"
static void traverseLeft(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    ((XfwfCommonWidgetClass)self->core.widget_class)->xfwfCommon_class.traverse(self, TraverseLeft, self, &event->xkey.time);
}

/*ARGSUSED*/
#line 1053 "Common.w"
static void traverseRight(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    ((XfwfCommonWidgetClass)self->core.widget_class)->xfwfCommon_class.traverse(self, TraverseRight, self, &event->xkey.time);
}

/*ARGSUSED*/
#line 1065 "Common.w"
static void traverseNext(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    ((XfwfCommonWidgetClass)self->core.widget_class)->xfwfCommon_class.traverse(self, TraverseNext, self, &event->xkey.time);
}

/*ARGSUSED*/
#line 1074 "Common.w"
static void traversePrev(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    ((XfwfCommonWidgetClass)self->core.widget_class)->xfwfCommon_class.traverse(self, TraversePrev, self, &event->xkey.time);
}

/*ARGSUSED*/
#line 1085 "Common.w"
static void traverseNextTop(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    ((XfwfCommonWidgetClass)self->core.widget_class)->xfwfCommon_class.traverse(self, TraverseNextTop, self, &event->xkey.time);
}

/*ARGSUSED*/
#line 1094 "Common.w"
static void traverseHome(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    ((XfwfCommonWidgetClass)self->core.widget_class)->xfwfCommon_class.traverse(self, TraverseHome, self, &event->xkey.time);
}

/*ARGSUSED*/
#line 1104 "Common.w"
static void traverseCurrent(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    Time time = CurrentTime;

    if (((XfwfCommonWidget)self)->xfwfCommon.traversalOn) (void) ((XfwfCommonWidgetClass)self->core.widget_class)->core_class.accept_focus(self, &time);
}

static void _resolve_inheritance(class)
WidgetClass class;
{
  XfwfCommonWidgetClass c = (XfwfCommonWidgetClass) class;
  XfwfCommonWidgetClass super;
  static CompositeClassExtensionRec extension_rec = {
    NULL, NULLQUARK, XtCompositeExtensionVersion,
    sizeof(CompositeClassExtensionRec), True};
  CompositeClassExtensionRec *ext;
  ext = (XtPointer)XtMalloc(sizeof(*ext));
  *ext = extension_rec;
  ext->next_extension = c->composite_class.extension;
  c->composite_class.extension = ext;
  if (class == xfwfCommonWidgetClass) return;
  super = (XfwfCommonWidgetClass)class->core_class.superclass;
  if (c->xfwfCommon_class.compute_inside == XtInherit_compute_inside)
    c->xfwfCommon_class.compute_inside = super->xfwfCommon_class.compute_inside;
  if (c->xfwfCommon_class.total_frame_width == XtInherit_total_frame_width)
    c->xfwfCommon_class.total_frame_width = super->xfwfCommon_class.total_frame_width;
  if (c->xfwfCommon_class.highlight_border == XtInherit_highlight_border)
    c->xfwfCommon_class.highlight_border = super->xfwfCommon_class.highlight_border;
  if (c->xfwfCommon_class.unhighlight_border == XtInherit_unhighlight_border)
    c->xfwfCommon_class.unhighlight_border = super->xfwfCommon_class.unhighlight_border;
  if (c->xfwfCommon_class.would_accept_focus == XtInherit_would_accept_focus)
    c->xfwfCommon_class.would_accept_focus = super->xfwfCommon_class.would_accept_focus;
  if (c->xfwfCommon_class.traverse == XtInherit_traverse)
    c->xfwfCommon_class.traverse = super->xfwfCommon_class.traverse;
  if (c->xfwfCommon_class.lighter_color == XtInherit_lighter_color)
    c->xfwfCommon_class.lighter_color = super->xfwfCommon_class.lighter_color;
  if (c->xfwfCommon_class.darker_color == XtInherit_darker_color)
    c->xfwfCommon_class.darker_color = super->xfwfCommon_class.darker_color;
}
#line 259 "Common.w"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 259 "Common.w"
static void class_initialize(void)
#else
#line 259 "Common.w"
static void class_initialize()
#endif
#line 260 "Common.w"
{
#ifndef NO_XPM
    static XtConvertArgRec args[] = {
	{ XtWidgetBaseOffset,
          0,
          sizeof(Widget) },
	{ XtWidgetBaseOffset,
	  (XtPointer) XtOffsetOf(XfwfCommonRec, core.colormap),
	  sizeof(Colormap) },
	{ XtWidgetBaseOffset,
	  (XtPointer) XtOffsetOf(XfwfCommonRec, xfwfCommon.xcc),
	  sizeof(XCC) } };
#endif
    static XtConvertArgRec colorargs[] = {
	{ XtWidgetBaseOffset,
	  (XtPointer) XtOffsetOf(XfwfCommonRec, core.colormap),
	  sizeof(Colormap) },
	{ XtWidgetBaseOffset,
	  (XtPointer) XtOffsetOf(XfwfCommonRec, xfwfCommon.xcc),
	  sizeof(XCC) } };

    XtSetTypeConverter(XtRString, "Alignment", cvtStringToAlignment,
		       NULL, 0, XtCacheNone, NULL);
    XtSetTypeConverter("Alignment", XtRString, cvtAlignmentToString,
		       NULL, 0, XtCacheNone, NULL);
    /* init_icon_quarks(); */
#ifndef NO_XPM
    XtSetTypeConverter(XtRString, "Icon", cvtStringToIcon,
		       args, XtNumber(args), XtCacheByDisplay,
		       cvtIconDestructor);
#endif
    XtSetTypeConverter(XtRString, "StringArray", cvtStringToStringArray,
		       NULL, 0, XtCacheNone, NULL);
    XtSetTypeConverter(XtRString, XtRColor, cvtStringToColor,
		       colorargs, XtNumber(colorargs), XtCacheNone, NULL);
}
#line 306 "Common.w"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 306 "Common.w"
static void initialize(Widget  request,Widget self,ArgList  args,Cardinal * num_args)
#else
#line 306 "Common.w"
static void initialize(request,self,args,num_args)Widget  request;Widget self;ArgList  args;Cardinal * num_args;
#endif
#line 307 "Common.w"
{
    Dimension frame;

    if (((XfwfCommonWidgetClass)self->core.widget_class)->xfwfCommon_class.traversal_trans == NULL)
	((XfwfCommonWidgetClass)self->core.widget_class)->xfwfCommon_class.traversal_trans = XtParseTranslationTable(extraTranslations);
    if (((XfwfCommonWidget)self)->xfwfCommon.traversalOn) {
	XtAugmentTranslations(self, ((XfwfCommonWidgetClass)self->core.widget_class)->xfwfCommon_class.traversal_trans);
	((XfwfCommonWidgetClass)self->core.widget_class)->core_class.visible_interest = True;
    }
    ((XfwfCommonWidget)self)->xfwfCommon.traversal_focus = FALSE;
    ((XfwfCommonWidget)self)->xfwfCommon.bordergc = NULL;
    frame = ((XfwfCommonWidgetClass)self->core.widget_class)->xfwfCommon_class.total_frame_width(self);
    if (((XfwfCommonWidget)self)->core.width < 2 * frame + 2) ((XfwfCommonWidget)self)->core.width = 2 * frame + 2;
    if (((XfwfCommonWidget)self)->core.height < 2 * frame + 2) ((XfwfCommonWidget)self)->core.height = 2 * frame + 2;
    if (((XfwfCommonWidget)self)->core.width == 0) ((XfwfCommonWidget)self)->core.width = 2;
    if (((XfwfCommonWidget)self)->core.height == 0) ((XfwfCommonWidget)self)->core.height = 2;
    create_bordergc(self);
    ((XfwfCommonWidget)self)->core.background_pixel = ((XfwfCommonWidget)self)->xfwfCommon.background;
    ((XfwfCommonWidget)self)->core.visible = FALSE;				/* Why is this needed? */
    /* fprintf(stderr, "initialize(%s): visible=%s\n",
       XtName($), $visible?"TRUE":"FALSE"); */
}
#line 339 "Common.w"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 339 "Common.w"
static Boolean  set_values(Widget  old,Widget  request,Widget self,ArgList  args,Cardinal * num_args)
#else
#line 339 "Common.w"
static Boolean  set_values(old,request,self,args,num_args)Widget  old;Widget  request;Widget self;ArgList  args;Cardinal * num_args;
#endif
#line 340 "Common.w"
{
    Boolean need_redraw = False;
    Widget parent = XtParent(self);
    Time time = CurrentTime;

    if (((XfwfCommonWidget)self)->xfwfCommon.traversalOn != ((XfwfCommonWidget)old)->xfwfCommon.traversalOn && ((XfwfCommonWidget)self)->xfwfCommon.traversalOn) {
	XtAugmentTranslations(self, ((XfwfCommonWidgetClass)self->core.widget_class)->xfwfCommon_class.traversal_trans); 
	((XfwfCommonWidgetClass)self->core.widget_class)->core_class.visible_interest = True;
    }
    if ((((XfwfCommonWidget)self)->core.sensitive != ((XfwfCommonWidget)old)->core.sensitive
	 || ((XfwfCommonWidget)self)->core.ancestor_sensitive != ((XfwfCommonWidget)old)->core.ancestor_sensitive
	 || ((XfwfCommonWidget)self)->xfwfCommon.traversalOn != ((XfwfCommonWidget)old)->xfwfCommon.traversalOn)
	&& ((XfwfCommonWidget)self)->xfwfCommon.traversal_focus) {
	if (XtIsSubclass(parent, xfwfCommonWidgetClass)) {
	    if (!((XfwfCommonWidget)self)->core.sensitive) {
		/*
		 * Necessary when $ is highlighted and $sensitive is
		 * changed to FALSE. When this is left out keyboard
		 * traversal doesn't work when $sensitive is changed back
		 * to TRUE.
		 */
		((XfwfCommonWidgetClass)self->core.widget_class)->xfwfCommon_class.unhighlight_border(self);
		((XfwfCommonWidget)self)->xfwfCommon.traversal_focus = FALSE;
	    }
	    ((XfwfCommonWidgetClass)parent->core.widget_class)->xfwfCommon_class.traverse(parent, TraverseHome, self, &time);
	}
    }
    if (((XfwfCommonWidget)self)->xfwfCommon.highlightThickness != ((XfwfCommonWidget)old)->xfwfCommon.highlightThickness)
	need_redraw = True;
    if (((XfwfCommonWidget)self)->xfwfCommon.highlightPixmap != ((XfwfCommonWidget)old)->xfwfCommon.highlightPixmap) {
	create_bordergc(self);
	need_redraw = True;
    } else if (((XfwfCommonWidget)self)->xfwfCommon.highlightColor != ((XfwfCommonWidget)old)->xfwfCommon.highlightColor) {
	((XfwfCommonWidget)self)->xfwfCommon.highlightPixmap = None;
	create_bordergc(self);
	need_redraw = True;
    }
    if (((XfwfCommonWidget)self)->xfwfCommon.background != ((XfwfCommonWidget)old)->xfwfCommon.background) {
        ((XfwfCommonWidget)self)->core.background_pixel = ((XfwfCommonWidget)self)->xfwfCommon.background;
        need_redraw = True;
    }
    return need_redraw;
}
#line 391 "Common.w"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 391 "Common.w"
static void compute_inside(Widget self,Position * x,Position * y,Dimension * w,Dimension * h)
#else
#line 391 "Common.w"
static void compute_inside(self,x,y,w,h)Widget self;Position * x;Position * y;Dimension * w;Dimension * h;
#endif
#line 392 "Common.w"
{
    *x = ((XfwfCommonWidget)self)->xfwfCommon.highlightThickness;
    *y = ((XfwfCommonWidget)self)->xfwfCommon.highlightThickness;
    *w = ((XfwfCommonWidget)self)->core.width - 2 * ((XfwfCommonWidget)self)->xfwfCommon.highlightThickness;
    *h = ((XfwfCommonWidget)self)->core.height - 2 * ((XfwfCommonWidget)self)->xfwfCommon.highlightThickness;
}
#line 403 "Common.w"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 403 "Common.w"
static Dimension  total_frame_width(Widget self)
#else
#line 403 "Common.w"
static Dimension  total_frame_width(self)Widget self;
#endif
#line 404 "Common.w"
{
    return ((XfwfCommonWidget)self)->xfwfCommon.highlightThickness;
}
#line 410 "Common.w"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 410 "Common.w"
static void expose(Widget self,XEvent * event,Region  region)
#else
#line 410 "Common.w"
static void expose(self,event,region)Widget self;XEvent * event;Region  region;
#endif
#line 411 "Common.w"
{
    if (! XtIsRealized(self)) return;
    if (region != NULL) XSetRegion(XtDisplay(self), ((XfwfCommonWidget)self)->xfwfCommon.bordergc, region);
    if (((XfwfCommonWidget)self)->xfwfCommon.traversal_focus) ((XfwfCommonWidgetClass)self->core.widget_class)->xfwfCommon_class.highlight_border(self);
    if (region != NULL) XSetClipMask(XtDisplay(self), ((XfwfCommonWidget)self)->xfwfCommon.bordergc, None);
}
#line 422 "Common.w"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 422 "Common.w"
static void destroy(Widget self)
#else
#line 422 "Common.w"
static void destroy(self)Widget self;
#endif
#line 423 "Common.w"
{
    Widget parent = XtParent(self);
    Time time = CurrentTime;

    if (((XfwfCommonWidget)self)->xfwfCommon.traversal_focus) {
	((XfwfCommonWidget)self)->core.sensitive = False;
	if (XtIsSubclass(parent, xfwfCommonWidgetClass))
	    ((XfwfCommonWidgetClass)parent->core.widget_class)->xfwfCommon_class.traverse(parent, TraverseHome, self, &time);
    }
    if (((XfwfCommonWidget)self)->xfwfCommon.own_xcc) XCCFree(((XfwfCommonWidget)self)->xfwfCommon.xcc);
}
#line 435 "Common.w"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 435 "Common.w"
static void realize(Widget self,XtValueMask * mask,XSetWindowAttributes * attributes)
#else
#line 435 "Common.w"
static void realize(self,mask,attributes)Widget self;XtValueMask * mask;XSetWindowAttributes * attributes;
#endif
#line 436 "Common.w"
{
    Widget p;

    compositeClassRec.core_class.realize(self, mask, attributes);
    p = self;
    do p = XtParent(p); while (!XtIsShell(p));
    if (((XfwfCommonWidget)self)->xfwfCommon.useXCC && XCCGetColormap(((XfwfCommonWidget)self)->xfwfCommon.xcc) != ((XfwfCommonWidget)p)->core.colormap)
        XtVaSetValues(p, XtNcolormap, XCCGetColormap(((XfwfCommonWidget)self)->xfwfCommon.xcc), NULL);
}
#line 451 "Common.w"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 451 "Common.w"
static void highlight_border(Widget self)
#else
#line 451 "Common.w"
static void highlight_border(self)Widget self;
#endif
#line 452 "Common.w"
{
    XRectangle rect[4];

    if (((XfwfCommonWidget)self)->xfwfCommon.highlightThickness == 0) return;

    rect[0].x = 0;
    rect[0].y = 0;
    rect[0].width = ((XfwfCommonWidget)self)->core.width;
    rect[0].height = ((XfwfCommonWidget)self)->xfwfCommon.highlightThickness;

    rect[1].x = 0;
    rect[1].y = 0;
    rect[1].width = ((XfwfCommonWidget)self)->xfwfCommon.highlightThickness;
    rect[1].height = ((XfwfCommonWidget)self)->core.height;

    rect[2].x = ((XfwfCommonWidget)self)->core.width - ((XfwfCommonWidget)self)->xfwfCommon.highlightThickness;
    rect[2].y = 0;
    rect[2].width = ((XfwfCommonWidget)self)->xfwfCommon.highlightThickness;
    rect[2].height = ((XfwfCommonWidget)self)->core.height;

    rect[3].x = 0;
    rect[3].y = ((XfwfCommonWidget)self)->core.height - ((XfwfCommonWidget)self)->xfwfCommon.highlightThickness;
    rect[3].width = ((XfwfCommonWidget)self)->core.width;
    rect[3].height = ((XfwfCommonWidget)self)->xfwfCommon.highlightThickness;

    XFillRectangles(XtDisplay(self), XtWindow(self), ((XfwfCommonWidget)self)->xfwfCommon.bordergc, &rect[0], 4);
}
#line 480 "Common.w"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 480 "Common.w"
static void unhighlight_border(Widget self)
#else
#line 480 "Common.w"
static void unhighlight_border(self)Widget self;
#endif
#line 481 "Common.w"
{
    if (((XfwfCommonWidget)self)->xfwfCommon.highlightThickness == 0) return;

    XClearArea(XtDisplay(self), XtWindow(self), 
	       0, 0, ((XfwfCommonWidget)self)->core.width, ((XfwfCommonWidget)self)->xfwfCommon.highlightThickness, False);
    XClearArea(XtDisplay(self), XtWindow(self),
	       0, 0, ((XfwfCommonWidget)self)->xfwfCommon.highlightThickness, ((XfwfCommonWidget)self)->core.height, False);
    XClearArea(XtDisplay(self), XtWindow(self),
	       ((XfwfCommonWidget)self)->core.width - ((XfwfCommonWidget)self)->xfwfCommon.highlightThickness, 0, 
	       ((XfwfCommonWidget)self)->xfwfCommon.highlightThickness, ((XfwfCommonWidget)self)->core.height, False);
    XClearArea(XtDisplay(self), XtWindow(self),
	       0, ((XfwfCommonWidget)self)->core.height - ((XfwfCommonWidget)self)->xfwfCommon.highlightThickness,
	       ((XfwfCommonWidget)self)->core.width, ((XfwfCommonWidget)self)->xfwfCommon.highlightThickness, False);
}
#line 505 "Common.w"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 505 "Common.w"
static Boolean  accept_focus(Widget self,Time * time)
#else
#line 505 "Common.w"
static Boolean  accept_focus(self,time)Widget self;Time * time;
#endif
#line 506 "Common.w"
{
    int i;

    /* fprintf(stderr, "accept_focus(%s): visible=%s\n",
       XtName($), $visible?"TRUE":"FALSE"); */
    if (! XtIsRealized(self) || ! XtIsSensitive(self) || ! ((XfwfCommonWidget)self)->xfwfCommon.traversalOn
	|| ! ((XfwfCommonWidget)self)->core.visible || ! ((XfwfCommonWidget)self)->core.ancestor_sensitive || ((XfwfCommonWidget)self)->core.being_destroyed)
	return FALSE;
    for (i = 0; i < ((XfwfCommonWidget)self)->composite.num_children; i++)
        if (XtCallAcceptFocus(((XfwfCommonWidget)self)->composite.children[i], time)) return TRUE;
    if (! ((XfwfCommonWidget)self)->xfwfCommon.traversal_focus) {
	XSetInputFocus(XtDisplay(self), XtWindow(self), RevertToParent, *time);
	((XfwfCommonWidget)self)->xfwfCommon.traversal_focus = True;
	((XfwfCommonWidgetClass)self->core.widget_class)->xfwfCommon_class.highlight_border(self);
    }
    return TRUE;
}
#line 529 "Common.w"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 529 "Common.w"
static Boolean  would_accept_focus(Widget self)
#else
#line 529 "Common.w"
static Boolean  would_accept_focus(self)Widget self;
#endif
#line 530 "Common.w"
{
    int i;
    Widget child;

    if (! XtIsRealized(self) || ! XtIsSensitive(self) || ! ((XfwfCommonWidget)self)->xfwfCommon.traversalOn
	|| ! ((XfwfCommonWidget)self)->core.visible || ! ((XfwfCommonWidget)self)->core.ancestor_sensitive || ((XfwfCommonWidget)self)->core.being_destroyed)
	return FALSE;
    else {
        for (i = 0; i < ((XfwfCommonWidget)self)->composite.num_children; i++) {
            child = ((XfwfCommonWidget)self)->composite.children[i];
            if (XtIsSubclass(child, xfwfCommonWidgetClass)
                && ((XfwfCommonWidgetClass)child->core.widget_class)->xfwfCommon_class.would_accept_focus(child))
                return FALSE;
	}
        return TRUE;
    }
}
#define LARGE_NUMBER 2000000000 


#line 640 "Common.w"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 640 "Common.w"
static void traverse(Widget self,TraversalDirection  dir,Widget  current,Time * time)
#else
#line 640 "Common.w"
static void traverse(self,dir,current,time)Widget self;TraversalDirection  dir;Widget  current;Time * time;
#endif
#line 641 "Common.w"
{
    Widget w, parent = XtParent(self);
    Position x, y;
    int distance = LARGE_NUMBER;

    if (dir == TraverseNextTop)
	traverse_to_next_top(self, current, time);
    else if (dir == TraverseNext)
        traverse_to_next(self, current, time);
    else if (dir == TraversePrev)
        traverse_to_prev(self, current, time);
    else if (XtIsSubclass(parent, xfwfCommonWidgetClass))
        ((XfwfCommonWidgetClass)parent->core.widget_class)->xfwfCommon_class.traverse(parent, dir, current, time);
    else {
        if (((XfwfCommonWidget)self)->core.being_destroyed) return;                    /* LW, 951114 */
        switch (dir) {
        case TraverseHome: x = 0; y = 0; break;
        case TraverseLeft: x = 0; y = ((XfwfCommonWidget)current)->core.height/2; break;
        case TraverseDown: x = ((XfwfCommonWidget)current)->core.width/2; y = ((XfwfCommonWidget)current)->core.height; break;
        case TraverseRight: x = ((XfwfCommonWidget)current)->core.width; y = ((XfwfCommonWidget)current)->core.height/2; break;
        case TraverseUp: x = ((XfwfCommonWidget)current)->core.width/2; y = 0; break;
        }
        if (dir != TraverseHome) XtTranslateCoords(current, x, y, &x, &y);
        if (traverse_to_direction(self, dir, x, y, &w, &distance))
            XtCallAcceptFocus(w, time);
    }
}
#line 937 "Common.w"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 937 "Common.w"
static Boolean  lighter_color(Widget self,Pixel  base,Pixel * result)
#else
#line 937 "Common.w"
static Boolean  lighter_color(self,base,result)Widget self;Pixel  base;Pixel * result;
#endif
#line 938 "Common.w"
{
    if (! ((XfwfCommonWidget)self)->xfwfCommon.useXCC) {
        return choose_color(self, 1.5 /* was 1.35 */, base, result);
    } else {
        assert(((XfwfCommonWidget)self)->xfwfCommon.xcc != NULL);
        choose_xcc_color(self, ((XfwfCommonWidget)self)->xfwfCommon.xcc, 1.5 /* was 1.35 */, base, result);
        return TRUE;
    }
}
#line 953 "Common.w"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 953 "Common.w"
static Boolean  darker_color(Widget self,Pixel  base,Pixel * result)
#else
#line 953 "Common.w"
static Boolean  darker_color(self,base,result)Widget self;Pixel  base;Pixel * result;
#endif
#line 954 "Common.w"
{
    if (! ((XfwfCommonWidget)self)->xfwfCommon.useXCC) {
        return choose_color(self, 0.5 /* was 0.6 */, base, result);
    } else {
        assert(((XfwfCommonWidget)self)->xfwfCommon.xcc != NULL);
        choose_xcc_color(self, ((XfwfCommonWidget)self)->xfwfCommon.xcc, 0.5 /* was 0.6 */, base, result);
        return TRUE;
    }
}
#line 36 "Common.w"
#line 41 "Common.w"
#line 42 "Common.w"
#line 43 "Common.w"
#line 44 "Common.w"
#line 45 "Common.w"
#line 51 "Common.w"
#line 52 "Common.w"
#line 53 "Common.w"
#line 54 "Common.w"
#line 60 "Common.w"
#line 67 "Common.w"
#line 74 "Common.w"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 74 "Common.w"
void XfwfCallComputeInside(Widget self,Position * x,Position * y,Dimension * w,Dimension * h)
#else
#line 74 "Common.w"
void XfwfCallComputeInside(self,x,y,w,h)Widget self;Position * x;Position * y;Dimension * w;Dimension * h;
#endif
#line 75 "Common.w"
{
    if (XtIsSubclass(self, xfwfCommonWidgetClass) && ((XfwfCommonWidgetClass)self->core.widget_class)->xfwfCommon_class.compute_inside)
	((XfwfCommonWidgetClass)self->core.widget_class)->xfwfCommon_class.compute_inside(self, x, y, w, h);
    else 
	XtWarning
	    ("XfwfCallComputeInside only applies to subclasses of Common");
}
#line 87 "Common.w"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 87 "Common.w"
Dimension  XfwfCallFrameWidth(Widget self)
#else
#line 87 "Common.w"
Dimension  XfwfCallFrameWidth(self)Widget self;
#endif
#line 88 "Common.w"
{
    if (XtIsSubclass(self, xfwfCommonWidgetClass) && ((XfwfCommonWidgetClass)self->core.widget_class)->xfwfCommon_class.total_frame_width)
	return ((XfwfCommonWidgetClass)self->core.widget_class)->xfwfCommon_class.total_frame_width(self);
    else 
	XtWarning
	    ("XfwfCallFrameWidth only applies to subclasses of Common");
    return 0;
}
#line 99 "Common.w"
