/* XPM */
static char * wheel2 [] = {
/* width height ncolors cpp [x_hot y_hot] */
"15 64 11 1 0 0",
/* colors */
" 	s iconColor1	m black	c black",
".	s iconColor6	m white	c yellow",
"X	s iconGray8	m black	c #323232323232",
"o	s iconColor2	m white	c white",
"O	s iconGray6	m black	c #646464646464",
"+	s iconGray1	m white	c #e1e1e1e1e1e1",
"@	s iconGray2	m white	c #c8c8c8c8c8c8",
"#	s iconGray3	m white	c #afafafafafaf",
"$	s iconGray7	m black	c #4b4b4b4b4b4b",
"%	s iconGray4	m white	c #969696969696",
"&	s iconGray5	m black	c #7d7d7d7d7d7d",
/* pixels */
"               ",
"       .       ",
"XXXXXX...XXXXXX",
"XXXXX.....XXXXX",
"XXXX.......XXXX",
"XXX.........XXX",
"XX...........XX",
"X.............X",
"X              ",
"XoooooooooooooX",
"XOOOOOOOOOOOOOX",
"X+++++++++++++X",
"X+++++++++++++X",
"X+++++++++++++X",
"X+++++++++++++X",
"X@+@+@+@+@+@+@X",
"XoooooooooooooX",
"XOOOOOOOOOOOOOX",
"X@+@+@+@+@+@+@X",
"X@@@@@@@@@@@@@X",
"X+@+@+@+@+@+@+X",
"X@@@@@@@@@@@@@ ",
"X@@@@@@@@@@@@@X",
"X@@@@@@@@@@@@@X",
" @#@#@#@#@#@#@X",
" #@#@#@#@#@#@#X",
" oooooooooooooX",
" $$$$$$$$$$$$$X",
"X#############X",
"X#############X",
"X#############X",
" #############X",
"X#############X",
"X#############X",
"X#%#%#%#%#%#%#X",
"X%#%#%#%#%#%#%X",
" %%%%%%%%%%%%%X",
"X#%#%#%#%#%#%#X",
"XoooooooooooooX",
"X             X",
"X%%%%%%%%%%%%%X",
" %%%%%%%%%%%%%X",
"X%&%&%&%&%&%&%X",
"X&%&%&%&%&%&%&X",
"X&&&&&&&&&&&&&X",
"X&&&&&&&&&&&&&X",
" &&&&&&&&&&&&&X",
"X+++++++++++++X",
"X             X",
"XOOOOOOOOOOOOOX",
"XOOOOOOOOOOOOOX",
" OOOOOOOOOOOOOX",
"XOOOOOOOOOOOOOX",
"XOOOOOOOOOOOOOX",
"X#############X",
"X             X",
"X.............X",
"XX...........XX",
"XXX.........XXX",
"XXXX.......XXXX",
"XXXXX.....XXXXX",
"XXXXXX...XXXXXX",
"       .       ",
"               "};
