// Auto-generated by update_pdb_keys/generate_ir_tables.py
// Block: responses
#include "generated_ir_table_types.hpp"

namespace dakota::irgen::responses {

const std::unordered_map<std::string, KeyContract>& contracts() {
  static const auto kContracts = []() {
    std::unordered_map<std::string, KeyContract> m;
    m.reserve(57);
    m.emplace("calibration_data", KeyContract{IrValueType::Bool, DefaultSource::Policy, IRValue{bool(false)}});
    m.emplace("central_hess", KeyContract{IrValueType::Bool, DefaultSource::Schema, IRValue{bool(true)}});
    m.emplace("data_directory", KeyContract{IrValueType::String, DefaultSource::Policy, IRValue{std::string("")}});
    m.emplace("fd_gradient_step_size", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("fd_gradient_step_type", KeyContract{IrValueType::String, DefaultSource::Schema, IRValue{std::string("relative")}});
    m.emplace("fd_hessian_step_size", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("fd_hessian_step_type", KeyContract{IrValueType::String, DefaultSource::Schema, IRValue{std::string("relative")}});
    m.emplace("gradient_type", KeyContract{IrValueType::String, DefaultSource::Policy, IRValue{std::string("")}});
    m.emplace("gradients.mixed.id_analytic", KeyContract{IrValueType::IntSet, DefaultSource::Policy, IRValue{nlohmann::json::parse("{}")}});
    m.emplace("gradients.mixed.id_numerical", KeyContract{IrValueType::IntSet, DefaultSource::Policy, IRValue{nlohmann::json::parse("{}")}});
    m.emplace("hessian_type", KeyContract{IrValueType::String, DefaultSource::Policy, IRValue{std::string("")}});
    m.emplace("hessians.mixed.id_analytic", KeyContract{IrValueType::IntSet, DefaultSource::Policy, IRValue{nlohmann::json::parse("{}")}});
    m.emplace("hessians.mixed.id_numerical", KeyContract{IrValueType::IntSet, DefaultSource::Policy, IRValue{nlohmann::json::parse("{}")}});
    m.emplace("hessians.mixed.id_quasi", KeyContract{IrValueType::IntSet, DefaultSource::Policy, IRValue{nlohmann::json::parse("{}")}});
    m.emplace("id", KeyContract{IrValueType::String, DefaultSource::Policy, IRValue{std::string("")}});
    m.emplace("ignore_bounds", KeyContract{IrValueType::Bool, DefaultSource::Policy, IRValue{bool(false)}});
    m.emplace("interpolate", KeyContract{IrValueType::Bool, DefaultSource::Policy, IRValue{bool(false)}});
    m.emplace("interval_type", KeyContract{IrValueType::String, DefaultSource::Schema, IRValue{std::string("forward")}});
    m.emplace("labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("lengths", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("metadata_labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("method_source", KeyContract{IrValueType::String, DefaultSource::Schema, IRValue{std::string("dakota")}});
    m.emplace("nonlinear_equality_scale_types", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("nonlinear_equality_scales", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("nonlinear_equality_targets", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("nonlinear_inequality_lower_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("nonlinear_inequality_scale_types", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("nonlinear_inequality_scales", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("nonlinear_inequality_upper_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("num_calibration_terms", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("num_config_vars", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("num_coordinates_per_field", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("num_experiments", KeyContract{IrValueType::SizeT, DefaultSource::Schema, IRValue{static_cast<size_t>(1)}});
    m.emplace("num_field_calibration_terms", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("num_field_nonlinear_equality_constraints", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("num_field_nonlinear_inequality_constraints", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("num_field_objectives", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("num_field_responses", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("num_nonlinear_equality_constraints", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("num_nonlinear_inequality_constraints", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("num_objective_functions", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("num_response_functions", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("num_scalar_calibration_terms", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("num_scalar_nonlinear_equality_constraints", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("num_scalar_nonlinear_inequality_constraints", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("num_scalar_objectives", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("num_scalar_responses", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("primary_response_fn_scale_types", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("primary_response_fn_scales", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("primary_response_fn_sense", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("primary_response_fn_weights", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("quasi_hessian_type", KeyContract{IrValueType::String, DefaultSource::Policy, IRValue{std::string("")}});
    m.emplace("read_field_coordinates", KeyContract{IrValueType::Bool, DefaultSource::Policy, IRValue{bool(false)}});
    m.emplace("scalar_data_filename", KeyContract{IrValueType::String, DefaultSource::Policy, IRValue{std::string("")}});
    m.emplace("scalar_data_format", KeyContract{IrValueType::UnsignedShort, DefaultSource::Schema, IRValue{std::string("TABULAR_EXPER_ANNOT")}});
    m.emplace("simulation_variance", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("variance_type", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    return m;
  }();
  return kContracts;
}

const std::unordered_map<std::string, std::vector<WriteOp>>& instructions() {
  static const auto kInstructions = []() {
    std::unordered_map<std::string, std::vector<WriteOp>> m;
    m.reserve(117);
    m.emplace("descriptors", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "labels", nlohmann::json::parse("{\"handler_type\": \"strL\", \"keyword_name\": \"descriptors\", \"member_variable_type\": \"StringArray\"}")},
    });
    m.emplace("gradient_type/analytic_gradients", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceLiteral, "gradient_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"analytic_gradients\", \"member_variable_type\": \"String\", \"stored_value\": \"analytic\"}")},
    });
    m.emplace("gradient_type/mixed_gradients", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceLiteral, "gradient_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"mixed_gradients\", \"member_variable_type\": \"String\", \"stored_value\": \"mixed\"}")},
    });
    m.emplace("gradient_type/mixed_gradients/fd_step_size", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "fd_gradient_step_size", nlohmann::json::parse("{\"handler_type\": \"RealL\", \"keyword_name\": \"fd_step_size\", \"member_variable_type\": \"RealVector\"}")},
      WriteOp{OpKind::DirectValue, "fd_gradient_step_size", nlohmann::json::parse("{\"handler_type\": \"RealL\", \"keyword_name\": \"fd_step_size\", \"member_variable_type\": \"RealVector\"}")},
    });
    m.emplace("gradient_type/mixed_gradients/id_analytic_gradients", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "gradients.mixed.id_analytic", nlohmann::json::parse("{\"handler_type\": \"intset\", \"keyword_name\": \"id_analytic_gradients\", \"member_variable_type\": \"IntSet\"}")},
    });
    m.emplace("gradient_type/mixed_gradients/id_numerical_gradients", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "gradients.mixed.id_numerical", nlohmann::json::parse("{\"handler_type\": \"intset\", \"keyword_name\": \"id_numerical_gradients\", \"member_variable_type\": \"IntSet\"}")},
    });
    m.emplace("gradient_type/mixed_gradients/interval_type/central", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceLiteral, "interval_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"central\", \"member_variable_type\": \"String\", \"stored_value\": \"central\"}")},
      WriteOp{OpKind::PresenceLiteral, "interval_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"central\", \"member_variable_type\": \"String\", \"stored_value\": \"central\"}")},
    });
    m.emplace("gradient_type/mixed_gradients/interval_type/forward", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceLiteral, "interval_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"forward\", \"member_variable_type\": \"String\", \"stored_value\": \"forward\"}")},
      WriteOp{OpKind::PresenceLiteral, "interval_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"forward\", \"member_variable_type\": \"String\", \"stored_value\": \"forward\"}")},
    });
    m.emplace("gradient_type/mixed_gradients/method_source/dakota", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceLiteral, "method_source", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"dakota\", \"member_variable_type\": \"String\", \"stored_value\": \"dakota\"}")},
      WriteOp{OpKind::PresenceLiteral, "method_source", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"dakota\", \"member_variable_type\": \"String\", \"stored_value\": \"dakota\"}")},
    });
    m.emplace("gradient_type/mixed_gradients/method_source/dakota/ignore_bounds", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceBool, "ignore_bounds", nlohmann::json::parse("{\"handler_type\": \"true\", \"keyword_name\": \"ignore_bounds\", \"member_variable_type\": \"bool\"}")},
      WriteOp{OpKind::PresenceBool, "ignore_bounds", nlohmann::json::parse("{\"handler_type\": \"true\", \"keyword_name\": \"ignore_bounds\", \"member_variable_type\": \"bool\"}")},
    });
    m.emplace("gradient_type/mixed_gradients/method_source/dakota/step_scaling/absolute", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceLiteral, "fd_gradient_step_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"absolute\", \"member_variable_type\": \"String\", \"stored_value\": \"absolute\"}")},
      WriteOp{OpKind::PresenceLiteral, "fd_gradient_step_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"absolute\", \"member_variable_type\": \"String\", \"stored_value\": \"absolute\"}")},
    });
    m.emplace("gradient_type/mixed_gradients/method_source/dakota/step_scaling/bounds", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceLiteral, "fd_gradient_step_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"bounds\", \"member_variable_type\": \"String\", \"stored_value\": \"bounds\"}")},
      WriteOp{OpKind::PresenceLiteral, "fd_gradient_step_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"bounds\", \"member_variable_type\": \"String\", \"stored_value\": \"bounds\"}")},
    });
    m.emplace("gradient_type/mixed_gradients/method_source/dakota/step_scaling/relative", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceLiteral, "fd_gradient_step_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"relative\", \"member_variable_type\": \"String\", \"stored_value\": \"relative\"}")},
      WriteOp{OpKind::PresenceLiteral, "fd_gradient_step_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"relative\", \"member_variable_type\": \"String\", \"stored_value\": \"relative\"}")},
    });
    m.emplace("gradient_type/mixed_gradients/method_source/vendor", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceLiteral, "method_source", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"vendor\", \"member_variable_type\": \"String\", \"stored_value\": \"vendor\"}")},
      WriteOp{OpKind::PresenceLiteral, "method_source", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"vendor\", \"member_variable_type\": \"String\", \"stored_value\": \"vendor\"}")},
    });
    m.emplace("gradient_type/no_gradients", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceLiteral, "gradient_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"no_gradients\", \"member_variable_type\": \"String\", \"stored_value\": \"none\"}")},
    });
    m.emplace("gradient_type/numerical_gradients", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceLiteral, "gradient_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"numerical_gradients\", \"member_variable_type\": \"String\", \"stored_value\": \"numerical\"}")},
    });
    m.emplace("gradient_type/numerical_gradients/fd_step_size", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "fd_gradient_step_size", nlohmann::json::parse("{\"handler_type\": \"RealL\", \"keyword_name\": \"fd_step_size\", \"member_variable_type\": \"RealVector\"}")},
      WriteOp{OpKind::DirectValue, "fd_gradient_step_size", nlohmann::json::parse("{\"handler_type\": \"RealL\", \"keyword_name\": \"fd_step_size\", \"member_variable_type\": \"RealVector\"}")},
    });
    m.emplace("gradient_type/numerical_gradients/interval_type/central", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceLiteral, "interval_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"central\", \"member_variable_type\": \"String\", \"stored_value\": \"central\"}")},
      WriteOp{OpKind::PresenceLiteral, "interval_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"central\", \"member_variable_type\": \"String\", \"stored_value\": \"central\"}")},
    });
    m.emplace("gradient_type/numerical_gradients/interval_type/forward", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceLiteral, "interval_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"forward\", \"member_variable_type\": \"String\", \"stored_value\": \"forward\"}")},
      WriteOp{OpKind::PresenceLiteral, "interval_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"forward\", \"member_variable_type\": \"String\", \"stored_value\": \"forward\"}")},
    });
    m.emplace("gradient_type/numerical_gradients/method_source/dakota", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceLiteral, "method_source", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"dakota\", \"member_variable_type\": \"String\", \"stored_value\": \"dakota\"}")},
      WriteOp{OpKind::PresenceLiteral, "method_source", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"dakota\", \"member_variable_type\": \"String\", \"stored_value\": \"dakota\"}")},
    });
    m.emplace("gradient_type/numerical_gradients/method_source/dakota/ignore_bounds", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceBool, "ignore_bounds", nlohmann::json::parse("{\"handler_type\": \"true\", \"keyword_name\": \"ignore_bounds\", \"member_variable_type\": \"bool\"}")},
      WriteOp{OpKind::PresenceBool, "ignore_bounds", nlohmann::json::parse("{\"handler_type\": \"true\", \"keyword_name\": \"ignore_bounds\", \"member_variable_type\": \"bool\"}")},
    });
    m.emplace("gradient_type/numerical_gradients/method_source/dakota/step_scaling/absolute", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceLiteral, "fd_gradient_step_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"absolute\", \"member_variable_type\": \"String\", \"stored_value\": \"absolute\"}")},
      WriteOp{OpKind::PresenceLiteral, "fd_gradient_step_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"absolute\", \"member_variable_type\": \"String\", \"stored_value\": \"absolute\"}")},
    });
    m.emplace("gradient_type/numerical_gradients/method_source/dakota/step_scaling/bounds", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceLiteral, "fd_gradient_step_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"bounds\", \"member_variable_type\": \"String\", \"stored_value\": \"bounds\"}")},
      WriteOp{OpKind::PresenceLiteral, "fd_gradient_step_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"bounds\", \"member_variable_type\": \"String\", \"stored_value\": \"bounds\"}")},
    });
    m.emplace("gradient_type/numerical_gradients/method_source/dakota/step_scaling/relative", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceLiteral, "fd_gradient_step_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"relative\", \"member_variable_type\": \"String\", \"stored_value\": \"relative\"}")},
      WriteOp{OpKind::PresenceLiteral, "fd_gradient_step_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"relative\", \"member_variable_type\": \"String\", \"stored_value\": \"relative\"}")},
    });
    m.emplace("gradient_type/numerical_gradients/method_source/vendor", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceLiteral, "method_source", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"vendor\", \"member_variable_type\": \"String\", \"stored_value\": \"vendor\"}")},
      WriteOp{OpKind::PresenceLiteral, "method_source", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"vendor\", \"member_variable_type\": \"String\", \"stored_value\": \"vendor\"}")},
    });
    m.emplace("hessian_type/analytic_hessians", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceLiteral, "hessian_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"analytic_hessians\", \"member_variable_type\": \"String\", \"stored_value\": \"analytic\"}")},
    });
    m.emplace("hessian_type/mixed_hessians", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceLiteral, "hessian_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"mixed_hessians\", \"member_variable_type\": \"String\", \"stored_value\": \"mixed\"}")},
    });
    m.emplace("hessian_type/mixed_hessians/id_analytic_hessians", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "hessians.mixed.id_analytic", nlohmann::json::parse("{\"handler_type\": \"intset\", \"keyword_name\": \"id_analytic_hessians\", \"member_variable_type\": \"IntSet\"}")},
    });
    m.emplace("hessian_type/mixed_hessians/id_numerical_hessians/fd_step_size", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "fd_hessian_step_size", nlohmann::json::parse("{\"handler_type\": \"RealL\", \"keyword_name\": \"fd_step_size\", \"member_variable_type\": \"RealVector\"}")},
      WriteOp{OpKind::DirectValue, "fd_hessian_step_size", nlohmann::json::parse("{\"handler_type\": \"RealL\", \"keyword_name\": \"fd_step_size\", \"member_variable_type\": \"RealVector\"}")},
    });
    m.emplace("hessian_type/mixed_hessians/id_numerical_hessians/values", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "hessians.mixed.id_numerical", nlohmann::json::parse("{\"handler_type\": \"intset\", \"keyword_name\": \"id_numerical_hessians\", \"member_variable_type\": \"IntSet\"}")},
      WriteOp{OpKind::DirectValue, "hessians.mixed.id_numerical", nlohmann::json::parse("{\"handler_type\": \"intset\", \"keyword_name\": \"id_numerical_hessians\", \"member_variable_type\": \"IntSet\"}")},
    });
    m.emplace("hessian_type/mixed_hessians/id_quasi_hessians/approximation/bfgs", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceLiteral, "quasi_hessian_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"bfgs\", \"member_variable_type\": \"String\", \"stored_value\": \"bfgs\"}")},
      WriteOp{OpKind::PresenceLiteral, "quasi_hessian_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"bfgs\", \"member_variable_type\": \"String\", \"stored_value\": \"bfgs\"}")},
    });
    m.emplace("hessian_type/mixed_hessians/id_quasi_hessians/approximation/bfgs/damped", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceLiteral, "quasi_hessian_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"damped\", \"member_variable_type\": \"String\", \"stored_value\": \"damped_bfgs\"}")},
      WriteOp{OpKind::PresenceLiteral, "quasi_hessian_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"damped\", \"member_variable_type\": \"String\", \"stored_value\": \"damped_bfgs\"}")},
    });
    m.emplace("hessian_type/mixed_hessians/id_quasi_hessians/approximation/sr1", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceLiteral, "quasi_hessian_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"sr1\", \"member_variable_type\": \"String\", \"stored_value\": \"sr1\"}")},
      WriteOp{OpKind::PresenceLiteral, "quasi_hessian_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"sr1\", \"member_variable_type\": \"String\", \"stored_value\": \"sr1\"}")},
    });
    m.emplace("hessian_type/mixed_hessians/id_quasi_hessians/values", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "hessians.mixed.id_quasi", nlohmann::json::parse("{\"handler_type\": \"intset\", \"keyword_name\": \"id_quasi_hessians\", \"member_variable_type\": \"IntSet\"}")},
      WriteOp{OpKind::DirectValue, "hessians.mixed.id_quasi", nlohmann::json::parse("{\"handler_type\": \"intset\", \"keyword_name\": \"id_quasi_hessians\", \"member_variable_type\": \"IntSet\"}")},
    });
    m.emplace("hessian_type/mixed_hessians/interval_type/central", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceBool, "central_hess", nlohmann::json::parse("{\"handler_type\": \"true\", \"keyword_name\": \"central\", \"member_variable_type\": \"bool\"}")},
      WriteOp{OpKind::PresenceBool, "central_hess", nlohmann::json::parse("{\"handler_type\": \"true\", \"keyword_name\": \"central\", \"member_variable_type\": \"bool\"}")},
    });
    m.emplace("hessian_type/mixed_hessians/interval_type/forward", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "central_hess", nlohmann::json::parse("{\"handler_type\": \"false\", \"keyword_name\": \"forward\", \"member_variable_type\": \"bool\"}")},
      WriteOp{OpKind::DirectValue, "central_hess", nlohmann::json::parse("{\"handler_type\": \"false\", \"keyword_name\": \"forward\", \"member_variable_type\": \"bool\"}")},
    });
    m.emplace("hessian_type/mixed_hessians/step_scaling/absolute", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceLiteral, "fd_hessian_step_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"absolute\", \"member_variable_type\": \"String\", \"stored_value\": \"absolute\"}")},
      WriteOp{OpKind::PresenceLiteral, "fd_hessian_step_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"absolute\", \"member_variable_type\": \"String\", \"stored_value\": \"absolute\"}")},
    });
    m.emplace("hessian_type/mixed_hessians/step_scaling/bounds", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceLiteral, "fd_hessian_step_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"bounds\", \"member_variable_type\": \"String\", \"stored_value\": \"bounds\"}")},
      WriteOp{OpKind::PresenceLiteral, "fd_hessian_step_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"bounds\", \"member_variable_type\": \"String\", \"stored_value\": \"bounds\"}")},
    });
    m.emplace("hessian_type/mixed_hessians/step_scaling/relative", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceLiteral, "fd_hessian_step_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"relative\", \"member_variable_type\": \"String\", \"stored_value\": \"relative\"}")},
      WriteOp{OpKind::PresenceLiteral, "fd_hessian_step_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"relative\", \"member_variable_type\": \"String\", \"stored_value\": \"relative\"}")},
    });
    m.emplace("hessian_type/no_hessians", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceLiteral, "hessian_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"no_hessians\", \"member_variable_type\": \"String\", \"stored_value\": \"none\"}")},
    });
    m.emplace("hessian_type/numerical_hessians", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceLiteral, "hessian_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"numerical_hessians\", \"member_variable_type\": \"String\", \"stored_value\": \"numerical\"}")},
    });
    m.emplace("hessian_type/numerical_hessians/fd_step_size", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "fd_hessian_step_size", nlohmann::json::parse("{\"handler_type\": \"RealL\", \"keyword_name\": \"fd_step_size\", \"member_variable_type\": \"RealVector\"}")},
      WriteOp{OpKind::DirectValue, "fd_hessian_step_size", nlohmann::json::parse("{\"handler_type\": \"RealL\", \"keyword_name\": \"fd_step_size\", \"member_variable_type\": \"RealVector\"}")},
    });
    m.emplace("hessian_type/numerical_hessians/interval_type/central", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceBool, "central_hess", nlohmann::json::parse("{\"handler_type\": \"true\", \"keyword_name\": \"central\", \"member_variable_type\": \"bool\"}")},
      WriteOp{OpKind::PresenceBool, "central_hess", nlohmann::json::parse("{\"handler_type\": \"true\", \"keyword_name\": \"central\", \"member_variable_type\": \"bool\"}")},
    });
    m.emplace("hessian_type/numerical_hessians/interval_type/forward", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "central_hess", nlohmann::json::parse("{\"handler_type\": \"false\", \"keyword_name\": \"forward\", \"member_variable_type\": \"bool\"}")},
      WriteOp{OpKind::DirectValue, "central_hess", nlohmann::json::parse("{\"handler_type\": \"false\", \"keyword_name\": \"forward\", \"member_variable_type\": \"bool\"}")},
    });
    m.emplace("hessian_type/numerical_hessians/step_scaling/absolute", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceLiteral, "fd_hessian_step_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"absolute\", \"member_variable_type\": \"String\", \"stored_value\": \"absolute\"}")},
      WriteOp{OpKind::PresenceLiteral, "fd_hessian_step_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"absolute\", \"member_variable_type\": \"String\", \"stored_value\": \"absolute\"}")},
    });
    m.emplace("hessian_type/numerical_hessians/step_scaling/bounds", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceLiteral, "fd_hessian_step_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"bounds\", \"member_variable_type\": \"String\", \"stored_value\": \"bounds\"}")},
      WriteOp{OpKind::PresenceLiteral, "fd_hessian_step_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"bounds\", \"member_variable_type\": \"String\", \"stored_value\": \"bounds\"}")},
    });
    m.emplace("hessian_type/numerical_hessians/step_scaling/relative", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceLiteral, "fd_hessian_step_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"relative\", \"member_variable_type\": \"String\", \"stored_value\": \"relative\"}")},
      WriteOp{OpKind::PresenceLiteral, "fd_hessian_step_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"relative\", \"member_variable_type\": \"String\", \"stored_value\": \"relative\"}")},
    });
    m.emplace("hessian_type/quasi_hessians", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceLiteral, "hessian_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"quasi_hessians\", \"member_variable_type\": \"String\", \"stored_value\": \"quasi\"}")},
    });
    m.emplace("hessian_type/quasi_hessians/bfgs", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceLiteral, "quasi_hessian_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"bfgs\", \"member_variable_type\": \"String\", \"stored_value\": \"bfgs\"}")},
      WriteOp{OpKind::PresenceLiteral, "quasi_hessian_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"bfgs\", \"member_variable_type\": \"String\", \"stored_value\": \"bfgs\"}")},
    });
    m.emplace("hessian_type/quasi_hessians/bfgs/damped", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceLiteral, "quasi_hessian_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"damped\", \"member_variable_type\": \"String\", \"stored_value\": \"damped_bfgs\"}")},
      WriteOp{OpKind::PresenceLiteral, "quasi_hessian_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"damped\", \"member_variable_type\": \"String\", \"stored_value\": \"damped_bfgs\"}")},
    });
    m.emplace("hessian_type/quasi_hessians/sr1", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceLiteral, "quasi_hessian_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"sr1\", \"member_variable_type\": \"String\", \"stored_value\": \"sr1\"}")},
      WriteOp{OpKind::PresenceLiteral, "quasi_hessian_type", nlohmann::json::parse("{\"handler_type\": \"lit\", \"keyword_name\": \"sr1\", \"member_variable_type\": \"String\", \"stored_value\": \"sr1\"}")},
    });
    m.emplace("id_responses", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "id", nlohmann::json::parse("{\"handler_type\": \"str\", \"keyword_name\": \"id_responses\", \"member_variable_type\": \"String\"}")},
    });
    m.emplace("metadata", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "metadata_labels", nlohmann::json::parse("{\"handler_type\": \"strL\", \"keyword_name\": \"metadata\", \"member_variable_type\": \"StringArray\"}")},
    });
    m.emplace("response_type/calibration_terms/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "num_calibration_terms", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"calibration_terms\", \"member_variable_type\": \"size_t\"}")},
      WriteOp{OpKind::DirectValue, "num_calibration_terms", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"calibration_terms\", \"member_variable_type\": \"size_t\"}")},
    });
    m.emplace("response_type/calibration_terms/data_specification/calibration_data", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceBool, "calibration_data", nlohmann::json::parse("{\"handler_type\": \"true\", \"keyword_name\": \"calibration_data\", \"member_variable_type\": \"bool\"}")},
    });
    m.emplace("response_type/calibration_terms/data_specification/calibration_data/data_directory", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "data_directory", nlohmann::json::parse("{\"handler_type\": \"str\", \"keyword_name\": \"data_directory\", \"member_variable_type\": \"String\"}")},
    });
    m.emplace("response_type/calibration_terms/data_specification/calibration_data/experiment_variance_type", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "variance_type", nlohmann::json::parse("{\"handler_type\": \"strL\", \"keyword_name\": \"experiment_variance_type\", \"member_variable_type\": \"StringArray\"}")},
      WriteOp{OpKind::DirectValue, "variance_type", nlohmann::json::parse("{\"handler_type\": \"strL\", \"keyword_name\": \"experiment_variance_type\", \"member_variable_type\": \"StringArray\"}")},
    });
    m.emplace("response_type/calibration_terms/data_specification/calibration_data/interpolate", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceBool, "interpolate", nlohmann::json::parse("{\"handler_type\": \"true\", \"keyword_name\": \"interpolate\", \"member_variable_type\": \"bool\"}")},
    });
    m.emplace("response_type/calibration_terms/data_specification/calibration_data/num_config_variables", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "num_config_vars", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"num_config_variables\", \"member_variable_type\": \"size_t\"}")},
      WriteOp{OpKind::DirectValue, "num_config_vars", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"num_config_variables\", \"member_variable_type\": \"size_t\"}")},
    });
    m.emplace("response_type/calibration_terms/data_specification/calibration_data/num_experiments", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "num_experiments", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"num_experiments\", \"member_variable_type\": \"size_t\"}")},
      WriteOp{OpKind::DirectValue, "num_experiments", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"num_experiments\", \"member_variable_type\": \"size_t\"}")},
    });
    m.emplace("response_type/calibration_terms/data_specification/calibration_data/scalar_data_file/filename", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "scalar_data_filename", nlohmann::json::parse("{\"handler_type\": \"str\", \"keyword_name\": \"scalar_data_file\", \"member_variable_type\": \"String\"}")},
      WriteOp{OpKind::DirectValue, "scalar_data_filename", nlohmann::json::parse("{\"handler_type\": \"str\", \"keyword_name\": \"scalar_data_file\", \"member_variable_type\": \"String\"}")},
    });
    m.emplace("response_type/calibration_terms/data_specification/calibration_data/scalar_data_file/format/annotated", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceEnum, "scalar_data_format", nlohmann::json::parse("{\"handler_type\": \"utype\", \"keyword_name\": \"annotated\", \"member_variable_type\": \"unsigned short\", \"stored_value\": \"TABULAR_EXPER_ANNOT\"}")},
    });
    m.emplace("response_type/calibration_terms/data_specification/calibration_data/scalar_data_file/format/custom_annotated", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceEnum, "scalar_data_format", nlohmann::json::parse("{\"handler_type\": \"utype\", \"keyword_name\": \"custom_annotated\", \"member_variable_type\": \"unsigned short\", \"stored_value\": \"TABULAR_NONE\"}")},
    });
    m.emplace("response_type/calibration_terms/data_specification/calibration_data/scalar_data_file/format/custom_annotated/exp_id", std::vector<WriteOp>{
      WriteOp{OpKind::AugmentEnum, "scalar_data_format", nlohmann::json::parse("{\"handler_type\": \"augment_utype\", \"keyword_name\": \"exp_id\", \"member_variable_type\": \"unsigned short\", \"stored_value\": \"TABULAR_EVAL_ID\"}")},
    });
    m.emplace("response_type/calibration_terms/data_specification/calibration_data/scalar_data_file/format/custom_annotated/header", std::vector<WriteOp>{
      WriteOp{OpKind::AugmentEnum, "scalar_data_format", nlohmann::json::parse("{\"handler_type\": \"augment_utype\", \"keyword_name\": \"header\", \"member_variable_type\": \"unsigned short\", \"stored_value\": \"TABULAR_HEADER\"}")},
    });
    m.emplace("response_type/calibration_terms/data_specification/calibration_data/scalar_data_file/format/freeform", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceEnum, "scalar_data_format", nlohmann::json::parse("{\"handler_type\": \"utype\", \"keyword_name\": \"freeform\", \"member_variable_type\": \"unsigned short\", \"stored_value\": \"TABULAR_NONE\"}")},
    });
    m.emplace("response_type/calibration_terms/data_specification/calibration_data_file/experiment_variance_type", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "variance_type", nlohmann::json::parse("{\"handler_type\": \"strL\", \"keyword_name\": \"experiment_variance_type\", \"member_variable_type\": \"StringArray\"}")},
      WriteOp{OpKind::DirectValue, "variance_type", nlohmann::json::parse("{\"handler_type\": \"strL\", \"keyword_name\": \"experiment_variance_type\", \"member_variable_type\": \"StringArray\"}")},
    });
    m.emplace("response_type/calibration_terms/data_specification/calibration_data_file/filename", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "scalar_data_filename", nlohmann::json::parse("{\"handler_type\": \"str\", \"keyword_name\": \"calibration_data_file\", \"member_variable_type\": \"String\"}")},
      WriteOp{OpKind::DirectValue, "scalar_data_filename", nlohmann::json::parse("{\"handler_type\": \"str\", \"keyword_name\": \"calibration_data_file\", \"member_variable_type\": \"String\"}")},
    });
    m.emplace("response_type/calibration_terms/data_specification/calibration_data_file/format/annotated", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceEnum, "scalar_data_format", nlohmann::json::parse("{\"handler_type\": \"utype\", \"keyword_name\": \"annotated\", \"member_variable_type\": \"unsigned short\", \"stored_value\": \"TABULAR_EXPER_ANNOT\"}")},
    });
    m.emplace("response_type/calibration_terms/data_specification/calibration_data_file/format/custom_annotated", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceEnum, "scalar_data_format", nlohmann::json::parse("{\"handler_type\": \"utype\", \"keyword_name\": \"custom_annotated\", \"member_variable_type\": \"unsigned short\", \"stored_value\": \"TABULAR_NONE\"}")},
    });
    m.emplace("response_type/calibration_terms/data_specification/calibration_data_file/format/custom_annotated/exp_id", std::vector<WriteOp>{
      WriteOp{OpKind::AugmentEnum, "scalar_data_format", nlohmann::json::parse("{\"handler_type\": \"augment_utype\", \"keyword_name\": \"exp_id\", \"member_variable_type\": \"unsigned short\", \"stored_value\": \"TABULAR_EVAL_ID\"}")},
    });
    m.emplace("response_type/calibration_terms/data_specification/calibration_data_file/format/custom_annotated/header", std::vector<WriteOp>{
      WriteOp{OpKind::AugmentEnum, "scalar_data_format", nlohmann::json::parse("{\"handler_type\": \"augment_utype\", \"keyword_name\": \"header\", \"member_variable_type\": \"unsigned short\", \"stored_value\": \"TABULAR_HEADER\"}")},
    });
    m.emplace("response_type/calibration_terms/data_specification/calibration_data_file/format/freeform", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceEnum, "scalar_data_format", nlohmann::json::parse("{\"handler_type\": \"utype\", \"keyword_name\": \"freeform\", \"member_variable_type\": \"unsigned short\", \"stored_value\": \"TABULAR_NONE\"}")},
    });
    m.emplace("response_type/calibration_terms/data_specification/calibration_data_file/num_config_variables", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "num_config_vars", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"num_config_variables\", \"member_variable_type\": \"size_t\"}")},
      WriteOp{OpKind::DirectValue, "num_config_vars", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"num_config_variables\", \"member_variable_type\": \"size_t\"}")},
    });
    m.emplace("response_type/calibration_terms/data_specification/calibration_data_file/num_experiments", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "num_experiments", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"num_experiments\", \"member_variable_type\": \"size_t\"}")},
      WriteOp{OpKind::DirectValue, "num_experiments", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"num_experiments\", \"member_variable_type\": \"size_t\"}")},
    });
    m.emplace("response_type/calibration_terms/field_calibration_terms/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "num_field_calibration_terms", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"field_calibration_terms\", \"member_variable_type\": \"size_t\"}")},
      WriteOp{OpKind::DirectValue, "num_field_calibration_terms", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"field_calibration_terms\", \"member_variable_type\": \"size_t\"}")},
    });
    m.emplace("response_type/calibration_terms/field_calibration_terms/lengths", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "lengths", nlohmann::json::parse("{\"handler_type\": \"ivec\", \"keyword_name\": \"lengths\", \"member_variable_type\": \"IntVector\"}")},
      WriteOp{OpKind::DirectValue, "lengths", nlohmann::json::parse("{\"handler_type\": \"ivec\", \"keyword_name\": \"lengths\", \"member_variable_type\": \"IntVector\"}")},
      WriteOp{OpKind::DirectValue, "lengths", nlohmann::json::parse("{\"handler_type\": \"ivec\", \"keyword_name\": \"lengths\", \"member_variable_type\": \"IntVector\"}")},
    });
    m.emplace("response_type/calibration_terms/field_calibration_terms/num_coordinates_per_field", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "num_coordinates_per_field", nlohmann::json::parse("{\"handler_type\": \"ivec\", \"keyword_name\": \"num_coordinates_per_field\", \"member_variable_type\": \"IntVector\"}")},
      WriteOp{OpKind::DirectValue, "num_coordinates_per_field", nlohmann::json::parse("{\"handler_type\": \"ivec\", \"keyword_name\": \"num_coordinates_per_field\", \"member_variable_type\": \"IntVector\"}")},
      WriteOp{OpKind::DirectValue, "num_coordinates_per_field", nlohmann::json::parse("{\"handler_type\": \"ivec\", \"keyword_name\": \"num_coordinates_per_field\", \"member_variable_type\": \"IntVector\"}")},
    });
    m.emplace("response_type/calibration_terms/field_calibration_terms/read_field_coordinates", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceBool, "read_field_coordinates", nlohmann::json::parse("{\"handler_type\": \"true\", \"keyword_name\": \"read_field_coordinates\", \"member_variable_type\": \"bool\"}")},
      WriteOp{OpKind::PresenceBool, "read_field_coordinates", nlohmann::json::parse("{\"handler_type\": \"true\", \"keyword_name\": \"read_field_coordinates\", \"member_variable_type\": \"bool\"}")},
      WriteOp{OpKind::PresenceBool, "read_field_coordinates", nlohmann::json::parse("{\"handler_type\": \"true\", \"keyword_name\": \"read_field_coordinates\", \"member_variable_type\": \"bool\"}")},
    });
    m.emplace("response_type/calibration_terms/nonlinear_equality_constraints/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "num_nonlinear_equality_constraints", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"nonlinear_equality_constraints\", \"member_variable_type\": \"size_t\"}")},
      WriteOp{OpKind::DirectValue, "num_nonlinear_equality_constraints", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"nonlinear_equality_constraints\", \"member_variable_type\": \"size_t\"}")},
      WriteOp{OpKind::DirectValue, "num_nonlinear_equality_constraints", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"nonlinear_equality_constraints\", \"member_variable_type\": \"size_t\"}")},
      WriteOp{OpKind::DirectValue, "num_nonlinear_equality_constraints", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"nonlinear_equality_constraints\", \"member_variable_type\": \"size_t\"}")},
    });
    m.emplace("response_type/calibration_terms/nonlinear_equality_constraints/scale_types", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "nonlinear_equality_scale_types", nlohmann::json::parse("{\"handler_type\": \"strL\", \"keyword_name\": \"scale_types\", \"member_variable_type\": \"StringArray\"}")},
      WriteOp{OpKind::DirectValue, "nonlinear_equality_scale_types", nlohmann::json::parse("{\"handler_type\": \"strL\", \"keyword_name\": \"scale_types\", \"member_variable_type\": \"StringArray\"}")},
    });
    m.emplace("response_type/calibration_terms/nonlinear_equality_constraints/scales", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "nonlinear_equality_scales", nlohmann::json::parse("{\"handler_type\": \"RealDL\", \"keyword_name\": \"scales\", \"member_variable_type\": \"RealVector\"}")},
      WriteOp{OpKind::DirectValue, "nonlinear_equality_scales", nlohmann::json::parse("{\"handler_type\": \"RealDL\", \"keyword_name\": \"scales\", \"member_variable_type\": \"RealVector\"}")},
    });
    m.emplace("response_type/calibration_terms/nonlinear_equality_constraints/targets", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "nonlinear_equality_targets", nlohmann::json::parse("{\"handler_type\": \"RealDL\", \"keyword_name\": \"targets\", \"member_variable_type\": \"RealVector\"}")},
      WriteOp{OpKind::DirectValue, "nonlinear_equality_targets", nlohmann::json::parse("{\"handler_type\": \"RealDL\", \"keyword_name\": \"targets\", \"member_variable_type\": \"RealVector\"}")},
    });
    m.emplace("response_type/calibration_terms/nonlinear_inequality_constraints/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "num_nonlinear_inequality_constraints", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"nonlinear_inequality_constraints\", \"member_variable_type\": \"size_t\"}")},
      WriteOp{OpKind::DirectValue, "num_nonlinear_inequality_constraints", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"nonlinear_inequality_constraints\", \"member_variable_type\": \"size_t\"}")},
      WriteOp{OpKind::DirectValue, "num_nonlinear_inequality_constraints", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"nonlinear_inequality_constraints\", \"member_variable_type\": \"size_t\"}")},
      WriteOp{OpKind::DirectValue, "num_nonlinear_inequality_constraints", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"nonlinear_inequality_constraints\", \"member_variable_type\": \"size_t\"}")},
    });
    m.emplace("response_type/calibration_terms/nonlinear_inequality_constraints/lower_bounds", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "nonlinear_inequality_lower_bounds", nlohmann::json::parse("{\"handler_type\": \"RealDL\", \"keyword_name\": \"lower_bounds\", \"member_variable_type\": \"RealVector\"}")},
      WriteOp{OpKind::DirectValue, "nonlinear_inequality_lower_bounds", nlohmann::json::parse("{\"handler_type\": \"RealDL\", \"keyword_name\": \"lower_bounds\", \"member_variable_type\": \"RealVector\"}")},
    });
    m.emplace("response_type/calibration_terms/nonlinear_inequality_constraints/scale_types", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "nonlinear_inequality_scale_types", nlohmann::json::parse("{\"handler_type\": \"strL\", \"keyword_name\": \"scale_types\", \"member_variable_type\": \"StringArray\"}")},
      WriteOp{OpKind::DirectValue, "nonlinear_inequality_scale_types", nlohmann::json::parse("{\"handler_type\": \"strL\", \"keyword_name\": \"scale_types\", \"member_variable_type\": \"StringArray\"}")},
    });
    m.emplace("response_type/calibration_terms/nonlinear_inequality_constraints/scales", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "nonlinear_inequality_scales", nlohmann::json::parse("{\"handler_type\": \"RealDL\", \"keyword_name\": \"scales\", \"member_variable_type\": \"RealVector\"}")},
      WriteOp{OpKind::DirectValue, "nonlinear_inequality_scales", nlohmann::json::parse("{\"handler_type\": \"RealDL\", \"keyword_name\": \"scales\", \"member_variable_type\": \"RealVector\"}")},
    });
    m.emplace("response_type/calibration_terms/nonlinear_inequality_constraints/upper_bounds", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "nonlinear_inequality_upper_bounds", nlohmann::json::parse("{\"handler_type\": \"RealDL\", \"keyword_name\": \"upper_bounds\", \"member_variable_type\": \"RealVector\"}")},
      WriteOp{OpKind::DirectValue, "nonlinear_inequality_upper_bounds", nlohmann::json::parse("{\"handler_type\": \"RealDL\", \"keyword_name\": \"upper_bounds\", \"member_variable_type\": \"RealVector\"}")},
    });
    m.emplace("response_type/calibration_terms/primary_scales", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "primary_response_fn_scales", nlohmann::json::parse("{\"handler_type\": \"RealDL\", \"keyword_name\": \"primary_scales\", \"member_variable_type\": \"RealVector\"}")},
      WriteOp{OpKind::DirectValue, "primary_response_fn_scales", nlohmann::json::parse("{\"handler_type\": \"RealDL\", \"keyword_name\": \"primary_scales\", \"member_variable_type\": \"RealVector\"}")},
    });
    m.emplace("response_type/calibration_terms/scalar_calibration_terms", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "num_scalar_calibration_terms", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"scalar_calibration_terms\", \"member_variable_type\": \"size_t\"}")},
    });
    m.emplace("response_type/calibration_terms/simulation_variance", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "simulation_variance", nlohmann::json::parse("{\"handler_type\": \"RealL\", \"keyword_name\": \"simulation_variance\", \"member_variable_type\": \"RealVector\"}")},
    });
    m.emplace("response_type/calibration_terms/weights", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "primary_response_fn_weights", nlohmann::json::parse("{\"handler_type\": \"RealDL\", \"keyword_name\": \"weights\", \"member_variable_type\": \"RealVector\"}")},
      WriteOp{OpKind::DirectValue, "primary_response_fn_weights", nlohmann::json::parse("{\"handler_type\": \"RealDL\", \"keyword_name\": \"weights\", \"member_variable_type\": \"RealVector\"}")},
    });
    m.emplace("response_type/objective_functions/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "num_objective_functions", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"objective_functions\", \"member_variable_type\": \"size_t\"}")},
      WriteOp{OpKind::DirectValue, "num_objective_functions", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"objective_functions\", \"member_variable_type\": \"size_t\"}")},
    });
    m.emplace("response_type/objective_functions/field_objectives/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "num_field_objectives", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"field_objectives\", \"member_variable_type\": \"size_t\"}")},
      WriteOp{OpKind::DirectValue, "num_field_objectives", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"field_objectives\", \"member_variable_type\": \"size_t\"}")},
    });
    m.emplace("response_type/objective_functions/field_objectives/lengths", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "lengths", nlohmann::json::parse("{\"handler_type\": \"ivec\", \"keyword_name\": \"lengths\", \"member_variable_type\": \"IntVector\"}")},
      WriteOp{OpKind::DirectValue, "lengths", nlohmann::json::parse("{\"handler_type\": \"ivec\", \"keyword_name\": \"lengths\", \"member_variable_type\": \"IntVector\"}")},
      WriteOp{OpKind::DirectValue, "lengths", nlohmann::json::parse("{\"handler_type\": \"ivec\", \"keyword_name\": \"lengths\", \"member_variable_type\": \"IntVector\"}")},
    });
    m.emplace("response_type/objective_functions/field_objectives/num_coordinates_per_field", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "num_coordinates_per_field", nlohmann::json::parse("{\"handler_type\": \"ivec\", \"keyword_name\": \"num_coordinates_per_field\", \"member_variable_type\": \"IntVector\"}")},
      WriteOp{OpKind::DirectValue, "num_coordinates_per_field", nlohmann::json::parse("{\"handler_type\": \"ivec\", \"keyword_name\": \"num_coordinates_per_field\", \"member_variable_type\": \"IntVector\"}")},
      WriteOp{OpKind::DirectValue, "num_coordinates_per_field", nlohmann::json::parse("{\"handler_type\": \"ivec\", \"keyword_name\": \"num_coordinates_per_field\", \"member_variable_type\": \"IntVector\"}")},
    });
    m.emplace("response_type/objective_functions/field_objectives/read_field_coordinates", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceBool, "read_field_coordinates", nlohmann::json::parse("{\"handler_type\": \"true\", \"keyword_name\": \"read_field_coordinates\", \"member_variable_type\": \"bool\"}")},
      WriteOp{OpKind::PresenceBool, "read_field_coordinates", nlohmann::json::parse("{\"handler_type\": \"true\", \"keyword_name\": \"read_field_coordinates\", \"member_variable_type\": \"bool\"}")},
      WriteOp{OpKind::PresenceBool, "read_field_coordinates", nlohmann::json::parse("{\"handler_type\": \"true\", \"keyword_name\": \"read_field_coordinates\", \"member_variable_type\": \"bool\"}")},
    });
    m.emplace("response_type/objective_functions/nonlinear_equality_constraints/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "num_nonlinear_equality_constraints", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"nonlinear_equality_constraints\", \"member_variable_type\": \"size_t\"}")},
      WriteOp{OpKind::DirectValue, "num_nonlinear_equality_constraints", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"nonlinear_equality_constraints\", \"member_variable_type\": \"size_t\"}")},
      WriteOp{OpKind::DirectValue, "num_nonlinear_equality_constraints", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"nonlinear_equality_constraints\", \"member_variable_type\": \"size_t\"}")},
      WriteOp{OpKind::DirectValue, "num_nonlinear_equality_constraints", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"nonlinear_equality_constraints\", \"member_variable_type\": \"size_t\"}")},
    });
    m.emplace("response_type/objective_functions/nonlinear_equality_constraints/scale_types", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "nonlinear_equality_scale_types", nlohmann::json::parse("{\"handler_type\": \"strL\", \"keyword_name\": \"scale_types\", \"member_variable_type\": \"StringArray\"}")},
      WriteOp{OpKind::DirectValue, "nonlinear_equality_scale_types", nlohmann::json::parse("{\"handler_type\": \"strL\", \"keyword_name\": \"scale_types\", \"member_variable_type\": \"StringArray\"}")},
    });
    m.emplace("response_type/objective_functions/nonlinear_equality_constraints/scales", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "nonlinear_equality_scales", nlohmann::json::parse("{\"handler_type\": \"RealDL\", \"keyword_name\": \"scales\", \"member_variable_type\": \"RealVector\"}")},
      WriteOp{OpKind::DirectValue, "nonlinear_equality_scales", nlohmann::json::parse("{\"handler_type\": \"RealDL\", \"keyword_name\": \"scales\", \"member_variable_type\": \"RealVector\"}")},
    });
    m.emplace("response_type/objective_functions/nonlinear_equality_constraints/targets", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "nonlinear_equality_targets", nlohmann::json::parse("{\"handler_type\": \"RealDL\", \"keyword_name\": \"targets\", \"member_variable_type\": \"RealVector\"}")},
      WriteOp{OpKind::DirectValue, "nonlinear_equality_targets", nlohmann::json::parse("{\"handler_type\": \"RealDL\", \"keyword_name\": \"targets\", \"member_variable_type\": \"RealVector\"}")},
    });
    m.emplace("response_type/objective_functions/nonlinear_inequality_constraints/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "num_nonlinear_inequality_constraints", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"nonlinear_inequality_constraints\", \"member_variable_type\": \"size_t\"}")},
      WriteOp{OpKind::DirectValue, "num_nonlinear_inequality_constraints", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"nonlinear_inequality_constraints\", \"member_variable_type\": \"size_t\"}")},
      WriteOp{OpKind::DirectValue, "num_nonlinear_inequality_constraints", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"nonlinear_inequality_constraints\", \"member_variable_type\": \"size_t\"}")},
      WriteOp{OpKind::DirectValue, "num_nonlinear_inequality_constraints", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"nonlinear_inequality_constraints\", \"member_variable_type\": \"size_t\"}")},
    });
    m.emplace("response_type/objective_functions/nonlinear_inequality_constraints/lower_bounds", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "nonlinear_inequality_lower_bounds", nlohmann::json::parse("{\"handler_type\": \"RealDL\", \"keyword_name\": \"lower_bounds\", \"member_variable_type\": \"RealVector\"}")},
      WriteOp{OpKind::DirectValue, "nonlinear_inequality_lower_bounds", nlohmann::json::parse("{\"handler_type\": \"RealDL\", \"keyword_name\": \"lower_bounds\", \"member_variable_type\": \"RealVector\"}")},
    });
    m.emplace("response_type/objective_functions/nonlinear_inequality_constraints/scale_types", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "nonlinear_inequality_scale_types", nlohmann::json::parse("{\"handler_type\": \"strL\", \"keyword_name\": \"scale_types\", \"member_variable_type\": \"StringArray\"}")},
      WriteOp{OpKind::DirectValue, "nonlinear_inequality_scale_types", nlohmann::json::parse("{\"handler_type\": \"strL\", \"keyword_name\": \"scale_types\", \"member_variable_type\": \"StringArray\"}")},
    });
    m.emplace("response_type/objective_functions/nonlinear_inequality_constraints/scales", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "nonlinear_inequality_scales", nlohmann::json::parse("{\"handler_type\": \"RealDL\", \"keyword_name\": \"scales\", \"member_variable_type\": \"RealVector\"}")},
      WriteOp{OpKind::DirectValue, "nonlinear_inequality_scales", nlohmann::json::parse("{\"handler_type\": \"RealDL\", \"keyword_name\": \"scales\", \"member_variable_type\": \"RealVector\"}")},
    });
    m.emplace("response_type/objective_functions/nonlinear_inequality_constraints/upper_bounds", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "nonlinear_inequality_upper_bounds", nlohmann::json::parse("{\"handler_type\": \"RealDL\", \"keyword_name\": \"upper_bounds\", \"member_variable_type\": \"RealVector\"}")},
      WriteOp{OpKind::DirectValue, "nonlinear_inequality_upper_bounds", nlohmann::json::parse("{\"handler_type\": \"RealDL\", \"keyword_name\": \"upper_bounds\", \"member_variable_type\": \"RealVector\"}")},
    });
    m.emplace("response_type/objective_functions/primary_scale_types", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "primary_response_fn_scale_types", nlohmann::json::parse("{\"handler_type\": \"strL\", \"keyword_name\": \"primary_scale_types\", \"member_variable_type\": \"StringArray\"}")},
    });
    m.emplace("response_type/objective_functions/primary_scales", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "primary_response_fn_scales", nlohmann::json::parse("{\"handler_type\": \"RealDL\", \"keyword_name\": \"primary_scales\", \"member_variable_type\": \"RealVector\"}")},
      WriteOp{OpKind::DirectValue, "primary_response_fn_scales", nlohmann::json::parse("{\"handler_type\": \"RealDL\", \"keyword_name\": \"primary_scales\", \"member_variable_type\": \"RealVector\"}")},
    });
    m.emplace("response_type/objective_functions/scalar_objectives", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "num_scalar_objectives", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"scalar_objectives\", \"member_variable_type\": \"size_t\"}")},
    });
    m.emplace("response_type/objective_functions/sense", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "primary_response_fn_sense", nlohmann::json::parse("{\"handler_type\": \"strL\", \"keyword_name\": \"sense\", \"member_variable_type\": \"StringArray\"}")},
    });
    m.emplace("response_type/objective_functions/weights", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "primary_response_fn_weights", nlohmann::json::parse("{\"handler_type\": \"RealDL\", \"keyword_name\": \"weights\", \"member_variable_type\": \"RealVector\"}")},
      WriteOp{OpKind::DirectValue, "primary_response_fn_weights", nlohmann::json::parse("{\"handler_type\": \"RealDL\", \"keyword_name\": \"weights\", \"member_variable_type\": \"RealVector\"}")},
    });
    m.emplace("response_type/response_functions/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "num_response_functions", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"response_functions\", \"member_variable_type\": \"size_t\"}")},
      WriteOp{OpKind::DirectValue, "num_response_functions", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"response_functions\", \"member_variable_type\": \"size_t\"}")},
    });
    m.emplace("response_type/response_functions/field_responses/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "num_field_responses", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"field_responses\", \"member_variable_type\": \"size_t\"}")},
      WriteOp{OpKind::DirectValue, "num_field_responses", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"field_responses\", \"member_variable_type\": \"size_t\"}")},
    });
    m.emplace("response_type/response_functions/field_responses/lengths", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "lengths", nlohmann::json::parse("{\"handler_type\": \"ivec\", \"keyword_name\": \"lengths\", \"member_variable_type\": \"IntVector\"}")},
      WriteOp{OpKind::DirectValue, "lengths", nlohmann::json::parse("{\"handler_type\": \"ivec\", \"keyword_name\": \"lengths\", \"member_variable_type\": \"IntVector\"}")},
      WriteOp{OpKind::DirectValue, "lengths", nlohmann::json::parse("{\"handler_type\": \"ivec\", \"keyword_name\": \"lengths\", \"member_variable_type\": \"IntVector\"}")},
    });
    m.emplace("response_type/response_functions/field_responses/num_coordinates_per_field", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "num_coordinates_per_field", nlohmann::json::parse("{\"handler_type\": \"ivec\", \"keyword_name\": \"num_coordinates_per_field\", \"member_variable_type\": \"IntVector\"}")},
      WriteOp{OpKind::DirectValue, "num_coordinates_per_field", nlohmann::json::parse("{\"handler_type\": \"ivec\", \"keyword_name\": \"num_coordinates_per_field\", \"member_variable_type\": \"IntVector\"}")},
      WriteOp{OpKind::DirectValue, "num_coordinates_per_field", nlohmann::json::parse("{\"handler_type\": \"ivec\", \"keyword_name\": \"num_coordinates_per_field\", \"member_variable_type\": \"IntVector\"}")},
    });
    m.emplace("response_type/response_functions/field_responses/read_field_coordinates", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceBool, "read_field_coordinates", nlohmann::json::parse("{\"handler_type\": \"true\", \"keyword_name\": \"read_field_coordinates\", \"member_variable_type\": \"bool\"}")},
      WriteOp{OpKind::PresenceBool, "read_field_coordinates", nlohmann::json::parse("{\"handler_type\": \"true\", \"keyword_name\": \"read_field_coordinates\", \"member_variable_type\": \"bool\"}")},
      WriteOp{OpKind::PresenceBool, "read_field_coordinates", nlohmann::json::parse("{\"handler_type\": \"true\", \"keyword_name\": \"read_field_coordinates\", \"member_variable_type\": \"bool\"}")},
    });
    m.emplace("response_type/response_functions/scalar_responses", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "num_scalar_responses", nlohmann::json::parse("{\"handler_type\": \"sizet\", \"keyword_name\": \"scalar_responses\", \"member_variable_type\": \"size_t\"}")},
    });
    return m;
  }();
  return kInstructions;
}

} // namespace dakota::irgen::responses
