// Auto-generated by update_pdb_keys/generate_ir_tables.py
// Block: variables
#include "generated_ir_table_types.hpp"

namespace dakota::irgen::variables {

const std::unordered_map<std::string, KeyContract>& contracts() {
  static const auto kContracts = []() {
    std::unordered_map<std::string, KeyContract> m;
    m.reserve(289);
    m.emplace("beta_uncertain", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("beta_uncertain.alphas", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("beta_uncertain.betas", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("beta_uncertain.initial_point", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("beta_uncertain.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("beta_uncertain.lower_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("beta_uncertain.upper_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("binomial_uncertain", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("binomial_uncertain.categorical", KeyContract{IrValueType::BitArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("binomial_uncertain.initial_point", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("binomial_uncertain.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("binomial_uncertain.lower_bounds", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("binomial_uncertain.num_trials", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("binomial_uncertain.prob_per_trial", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("binomial_uncertain.upper_bounds", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("continuous_aleatory_uncertain.initial_point", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("continuous_aleatory_uncertain.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("continuous_aleatory_uncertain.lower_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("continuous_aleatory_uncertain.upper_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("continuous_design", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("continuous_design.initial_point", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("continuous_design.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("continuous_design.lower_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("continuous_design.scale_types", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("continuous_design.scales", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("continuous_design.upper_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("continuous_epistemic_uncertain.initial_point", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("continuous_epistemic_uncertain.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("continuous_epistemic_uncertain.lower_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("continuous_epistemic_uncertain.upper_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("continuous_interval_uncertain", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("continuous_interval_uncertain.basic_probs", KeyContract{IrValueType::RealRealPairRealMapArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("continuous_interval_uncertain.initial_point", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("continuous_interval_uncertain.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("continuous_interval_uncertain.lower_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("continuous_interval_uncertain.upper_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("continuous_state", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("continuous_state.initial_state", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("continuous_state.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("continuous_state.lower_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("continuous_state.upper_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_aleatory_uncertain_int.initial_point", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_aleatory_uncertain_int.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_aleatory_uncertain_int.lower_bounds", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_aleatory_uncertain_int.upper_bounds", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_aleatory_uncertain_real.initial_point", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_aleatory_uncertain_real.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_aleatory_uncertain_real.lower_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_aleatory_uncertain_real.upper_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_aleatory_uncertain_string.initial_point", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_aleatory_uncertain_string.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_aleatory_uncertain_string.lower_bounds", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_aleatory_uncertain_string.upper_bounds", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_design_range", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("discrete_design_range.categorical", KeyContract{IrValueType::BitArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_design_range.initial_point", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_design_range.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_design_range.lower_bounds", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_design_range.upper_bounds", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_design_set_int", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("discrete_design_set_int.adjacency_matrix", KeyContract{IrValueType::RealMatrixArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_design_set_int.categorical", KeyContract{IrValueType::BitArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_design_set_int.initial_point", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_design_set_int.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_design_set_int.lower_bounds", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_design_set_int.upper_bounds", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_design_set_int.values", KeyContract{IrValueType::IntSetArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_design_set_real", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("discrete_design_set_real.adjacency_matrix", KeyContract{IrValueType::RealMatrixArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_design_set_real.categorical", KeyContract{IrValueType::BitArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_design_set_real.initial_point", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_design_set_real.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_design_set_real.lower_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_design_set_real.upper_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_design_set_real.values", KeyContract{IrValueType::RealSetArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_design_set_str.adjacency_matrix", KeyContract{IrValueType::RealMatrixArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_design_set_string", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("discrete_design_set_string.initial_point", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_design_set_string.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_design_set_string.lower_bounds", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_design_set_string.upper_bounds", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_design_set_string.values", KeyContract{IrValueType::StringSetArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_epistemic_uncertain_int.initial_point", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_epistemic_uncertain_int.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_epistemic_uncertain_int.lower_bounds", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_epistemic_uncertain_int.upper_bounds", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_epistemic_uncertain_real.initial_point", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_epistemic_uncertain_real.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_epistemic_uncertain_real.lower_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_epistemic_uncertain_real.upper_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_epistemic_uncertain_string.initial_point", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_epistemic_uncertain_string.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_epistemic_uncertain_string.lower_bounds", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_epistemic_uncertain_string.upper_bounds", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_interval_uncertain", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("discrete_interval_uncertain.basic_probs", KeyContract{IrValueType::IntIntPairRealMapArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_interval_uncertain.categorical", KeyContract{IrValueType::BitArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_interval_uncertain.initial_point", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_interval_uncertain.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_interval_uncertain.lower_bounds", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_interval_uncertain.upper_bounds", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_state_range", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("discrete_state_range.categorical", KeyContract{IrValueType::BitArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_state_range.initial_state", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_state_range.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_state_range.lower_bounds", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_state_range.upper_bounds", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_state_set_int", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("discrete_state_set_int.categorical", KeyContract{IrValueType::BitArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_state_set_int.initial_state", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_state_set_int.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_state_set_int.lower_bounds", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_state_set_int.upper_bounds", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_state_set_int.values", KeyContract{IrValueType::IntSetArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_state_set_real", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("discrete_state_set_real.categorical", KeyContract{IrValueType::BitArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_state_set_real.initial_state", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_state_set_real.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_state_set_real.lower_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_state_set_real.upper_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_state_set_real.values", KeyContract{IrValueType::RealSetArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_state_set_string", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("discrete_state_set_string.initial_state", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_state_set_string.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_state_set_string.lower_bounds", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_state_set_string.upper_bounds", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_state_set_string.values", KeyContract{IrValueType::StringSetArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_uncertain_set_int", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("discrete_uncertain_set_int.categorical", KeyContract{IrValueType::BitArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_uncertain_set_int.initial_point", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_uncertain_set_int.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_uncertain_set_int.lower_bounds", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_uncertain_set_int.upper_bounds", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_uncertain_set_int.values_probs", KeyContract{IrValueType::IntRealMapArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_uncertain_set_real", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("discrete_uncertain_set_real.categorical", KeyContract{IrValueType::BitArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_uncertain_set_real.initial_point", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_uncertain_set_real.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_uncertain_set_real.lower_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_uncertain_set_real.upper_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_uncertain_set_real.values_probs", KeyContract{IrValueType::RealRealMapArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_uncertain_set_string", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("discrete_uncertain_set_string.initial_point", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_uncertain_set_string.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_uncertain_set_string.lower_bounds", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_uncertain_set_string.upper_bounds", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("discrete_uncertain_set_string.values_probs", KeyContract{IrValueType::StringRealMapArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("domain", KeyContract{IrValueType::Short, DefaultSource::Override, IRValue{std::string("DEFAULT_DOMAIN")}});
    m.emplace("exponential_uncertain", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("exponential_uncertain.betas", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("exponential_uncertain.initial_point", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("exponential_uncertain.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("exponential_uncertain.lower_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("exponential_uncertain.upper_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("frechet_uncertain", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("frechet_uncertain.alphas", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("frechet_uncertain.betas", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("frechet_uncertain.initial_point", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("frechet_uncertain.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("frechet_uncertain.lower_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("frechet_uncertain.upper_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("gamma_uncertain", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("gamma_uncertain.alphas", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("gamma_uncertain.betas", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("gamma_uncertain.initial_point", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("gamma_uncertain.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("gamma_uncertain.lower_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("gamma_uncertain.upper_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("geometric_uncertain", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("geometric_uncertain.categorical", KeyContract{IrValueType::BitArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("geometric_uncertain.initial_point", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("geometric_uncertain.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("geometric_uncertain.lower_bounds", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("geometric_uncertain.prob_per_trial", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("geometric_uncertain.upper_bounds", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("gumbel_uncertain", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("gumbel_uncertain.alphas", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("gumbel_uncertain.betas", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("gumbel_uncertain.initial_point", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("gumbel_uncertain.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("gumbel_uncertain.lower_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("gumbel_uncertain.upper_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("histogram_bin_uncertain.initial_point", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("histogram_bin_uncertain.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("histogram_bin_uncertain.lower_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("histogram_bin_uncertain.upper_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("histogram_uncertain.bin", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("histogram_uncertain.bin_pairs", KeyContract{IrValueType::RealRealMapArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("histogram_uncertain.point_int", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("histogram_uncertain.point_int.categorical", KeyContract{IrValueType::BitArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("histogram_uncertain.point_int.initial_point", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("histogram_uncertain.point_int.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("histogram_uncertain.point_int.lower_bounds", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("histogram_uncertain.point_int.upper_bounds", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("histogram_uncertain.point_int_pairs", KeyContract{IrValueType::IntRealMapArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("histogram_uncertain.point_real", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("histogram_uncertain.point_real.categorical", KeyContract{IrValueType::BitArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("histogram_uncertain.point_real.initial_point", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("histogram_uncertain.point_real.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("histogram_uncertain.point_real.lower_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("histogram_uncertain.point_real.upper_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("histogram_uncertain.point_real_pairs", KeyContract{IrValueType::RealRealMapArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("histogram_uncertain.point_string", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("histogram_uncertain.point_string.initial_point", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("histogram_uncertain.point_string.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("histogram_uncertain.point_string.lower_bounds", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("histogram_uncertain.point_string.upper_bounds", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("histogram_uncertain.point_string_pairs", KeyContract{IrValueType::StringRealMapArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("hypergeometric_uncertain", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("hypergeometric_uncertain.categorical", KeyContract{IrValueType::BitArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("hypergeometric_uncertain.initial_point", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("hypergeometric_uncertain.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("hypergeometric_uncertain.lower_bounds", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("hypergeometric_uncertain.num_drawn", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("hypergeometric_uncertain.selected_population", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("hypergeometric_uncertain.total_population", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("hypergeometric_uncertain.upper_bounds", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("id", KeyContract{IrValueType::String, DefaultSource::Policy, IRValue{std::string("")}});
    m.emplace("linear_equality_constraints", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("linear_equality_scale_types", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("linear_equality_scales", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("linear_equality_targets", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("linear_inequality_constraints", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("linear_inequality_lower_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("linear_inequality_scale_types", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("linear_inequality_scales", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("linear_inequality_upper_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("lognormal_uncertain", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("lognormal_uncertain.error_factors", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("lognormal_uncertain.inferred_lower_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("lognormal_uncertain.inferred_upper_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("lognormal_uncertain.initial_point", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("lognormal_uncertain.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("lognormal_uncertain.lambdas", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("lognormal_uncertain.lower_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("lognormal_uncertain.means", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("lognormal_uncertain.std_deviations", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("lognormal_uncertain.upper_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("lognormal_uncertain.zetas", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("loguniform_uncertain", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("loguniform_uncertain.initial_point", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("loguniform_uncertain.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("loguniform_uncertain.lower_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("loguniform_uncertain.upper_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("negative_binomial_uncertain", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("negative_binomial_uncertain.categorical", KeyContract{IrValueType::BitArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("negative_binomial_uncertain.initial_point", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("negative_binomial_uncertain.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("negative_binomial_uncertain.lower_bounds", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("negative_binomial_uncertain.num_trials", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("negative_binomial_uncertain.prob_per_trial", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("negative_binomial_uncertain.upper_bounds", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("normal_uncertain", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("normal_uncertain.inferred_lower_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("normal_uncertain.inferred_upper_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("normal_uncertain.initial_point", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("normal_uncertain.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("normal_uncertain.lower_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("normal_uncertain.means", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("normal_uncertain.std_deviations", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("normal_uncertain.upper_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("poisson_uncertain", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("poisson_uncertain.categorical", KeyContract{IrValueType::BitArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("poisson_uncertain.initial_point", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("poisson_uncertain.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("poisson_uncertain.lambdas", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("poisson_uncertain.lower_bounds", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("poisson_uncertain.upper_bounds", KeyContract{IrValueType::IntVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("triangular_uncertain", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("triangular_uncertain.initial_point", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("triangular_uncertain.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("triangular_uncertain.lower_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("triangular_uncertain.modes", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("triangular_uncertain.upper_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("uncertain.correlation_matrix", KeyContract{IrValueType::RealSymMatrix, DefaultSource::Policy, IRValue{nlohmann::json::parse("{}")}});
    m.emplace("uncertain.initial_point_flag", KeyContract{IrValueType::Bool, DefaultSource::Policy, IRValue{bool(false)}});
    m.emplace("uniform_uncertain", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("uniform_uncertain.initial_point", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("uniform_uncertain.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("uniform_uncertain.lower_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("uniform_uncertain.upper_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("view", KeyContract{IrValueType::Short, DefaultSource::Override, IRValue{std::string("DEFAULT_VIEW")}});
    m.emplace("weibull_uncertain", KeyContract{IrValueType::SizeT, DefaultSource::Policy, IRValue{static_cast<size_t>(0)}});
    m.emplace("weibull_uncertain.alphas", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("weibull_uncertain.betas", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("weibull_uncertain.initial_point", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("weibull_uncertain.labels", KeyContract{IrValueType::StringArray, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("weibull_uncertain.lower_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    m.emplace("weibull_uncertain.upper_bounds", KeyContract{IrValueType::RealVector, DefaultSource::Policy, IRValue{nlohmann::json::parse("[]")}});
    return m;
  }();
  return kContracts;
}

const std::unordered_map<std::string, std::vector<WriteOp>>& instructions() {
  static const auto kInstructions = []() {
    std::unordered_map<std::string, std::vector<WriteOp>> m;
    m.reserve(220);
    m.emplace("active/aleatory", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceEnum, "view", OpLiteral{IrValueType::String, IRValue{std::string("ALEATORY_UNCERTAIN_VIEW")}}},
    });
    m.emplace("active/all", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceEnum, "view", OpLiteral{IrValueType::String, IRValue{std::string("ALL_VIEW")}}},
    });
    m.emplace("active/design", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceEnum, "view", OpLiteral{IrValueType::String, IRValue{std::string("DESIGN_VIEW")}}},
    });
    m.emplace("active/epistemic", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceEnum, "view", OpLiteral{IrValueType::String, IRValue{std::string("EPISTEMIC_UNCERTAIN_VIEW")}}},
    });
    m.emplace("active/state", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceEnum, "view", OpLiteral{IrValueType::String, IRValue{std::string("STATE_VIEW")}}},
    });
    m.emplace("active/uncertain", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceEnum, "view", OpLiteral{IrValueType::String, IRValue{std::string("UNCERTAIN_VIEW")}}},
    });
    m.emplace("beta_uncertain", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "beta_uncertain", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("beta_uncertain/alphas", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "beta_uncertain.alphas", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("beta_uncertain/betas", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "beta_uncertain.betas", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("beta_uncertain/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "beta_uncertain", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("beta_uncertain/initial_point", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "beta_uncertain.initial_point", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("beta_uncertain/lower_bounds", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "beta_uncertain.lower_bounds", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("beta_uncertain/upper_bounds", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "beta_uncertain.upper_bounds", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("binomial_uncertain", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "binomial_uncertain", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("binomial_uncertain/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "binomial_uncertain", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("binomial_uncertain/initial_point", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "binomial_uncertain.initial_point", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("binomial_uncertain/num_trials", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "binomial_uncertain.num_trials", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("binomial_uncertain/probability_per_trial", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "binomial_uncertain.prob_per_trial", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("continuous_design", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "continuous_design", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("continuous_design/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "continuous_design", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("continuous_design/descriptors", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "continuous_design.labels", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("continuous_design/initial_point", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "continuous_design.initial_point", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("continuous_design/lower_bounds", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "continuous_design.lower_bounds", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("continuous_design/scale_types", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "continuous_design.scale_types", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("continuous_design/scales", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "continuous_design.scales", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("continuous_design/upper_bounds", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "continuous_design.upper_bounds", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("continuous_interval_uncertain", std::vector<WriteOp>{
      WriteOp{OpKind::ContinuousIntervalUncertain, "continuous_interval_uncertain.basic_probs", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("continuous_interval_uncertain/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "continuous_interval_uncertain", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("continuous_interval_uncertain/initial_point", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "continuous_interval_uncertain.initial_point", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("continuous_interval_uncertain/interval_probabilities", std::vector<WriteOp>{
      WriteOp{OpKind::ContinuousIntervalUncertain, "continuous_interval_uncertain.basic_probs", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("continuous_interval_uncertain/lower_bounds", std::vector<WriteOp>{
      WriteOp{OpKind::ContinuousIntervalUncertain, "continuous_interval_uncertain.basic_probs", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("continuous_interval_uncertain/upper_bounds", std::vector<WriteOp>{
      WriteOp{OpKind::ContinuousIntervalUncertain, "continuous_interval_uncertain.basic_probs", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("continuous_state", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "continuous_state", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("continuous_state/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "continuous_state", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("continuous_state/descriptors", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "continuous_state.labels", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("continuous_state/initial_state", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "continuous_state.initial_state", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("continuous_state/lower_bounds", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "continuous_state.lower_bounds", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("continuous_state/upper_bounds", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "continuous_state.upper_bounds", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_design_range", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_design_range", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_design_range/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_design_range", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_design_range/descriptors", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_design_range.labels", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_design_range/initial_point", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_design_range.initial_point", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_design_range/lower_bounds", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_design_range.lower_bounds", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_design_range/upper_bounds", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_design_range.upper_bounds", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_design_set/integer", std::vector<WriteOp>{
      WriteOp{OpKind::DiscreteSetValues, "discrete_design_set_int.values", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_design_set/integer/categorical", std::vector<WriteOp>{
      WriteOp{OpKind::Categorical, "discrete_design_set_int.categorical", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_design_set/integer/categorical/adjacency_matrix", std::vector<WriteOp>{
      WriteOp{OpKind::AdjacencyMatrix, "discrete_design_set_int.adjacency_matrix", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_design_set/integer/categorical/flags", std::vector<WriteOp>{
      WriteOp{OpKind::Categorical, "discrete_design_set_int.categorical", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_design_set/integer/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_design_set_int", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_design_set/integer/descriptors", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_design_set_int.labels", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_design_set/integer/elements", std::vector<WriteOp>{
      WriteOp{OpKind::DiscreteSetValues, "discrete_design_set_int.values", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_design_set/integer/initial_point", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_design_set_int.initial_point", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_design_set/real", std::vector<WriteOp>{
      WriteOp{OpKind::DiscreteSetValues, "discrete_design_set_real.values", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_design_set/real/categorical", std::vector<WriteOp>{
      WriteOp{OpKind::Categorical, "discrete_design_set_real.categorical", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_design_set/real/categorical/adjacency_matrix", std::vector<WriteOp>{
      WriteOp{OpKind::AdjacencyMatrix, "discrete_design_set_real.adjacency_matrix", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_design_set/real/categorical/flags", std::vector<WriteOp>{
      WriteOp{OpKind::Categorical, "discrete_design_set_real.categorical", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_design_set/real/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_design_set_real", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_design_set/real/descriptors", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_design_set_real.labels", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_design_set/real/elements", std::vector<WriteOp>{
      WriteOp{OpKind::DiscreteSetValues, "discrete_design_set_real.values", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_design_set/real/initial_point", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_design_set_real.initial_point", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_design_set/string", std::vector<WriteOp>{
      WriteOp{OpKind::DiscreteSetValues, "discrete_design_set_string.values", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_design_set/string/adjacency_matrix", std::vector<WriteOp>{
      WriteOp{OpKind::AdjacencyMatrix, "discrete_design_set_str.adjacency_matrix", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_design_set/string/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_design_set_string", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_design_set/string/descriptors", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_design_set_string.labels", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_design_set/string/elements", std::vector<WriteOp>{
      WriteOp{OpKind::DiscreteSetValues, "discrete_design_set_string.values", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_design_set/string/initial_point", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_design_set_string.initial_point", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_interval_uncertain", std::vector<WriteOp>{
      WriteOp{OpKind::DiscreteIntervalUncertain, "discrete_interval_uncertain.basic_probs", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_interval_uncertain/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_interval_uncertain", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_interval_uncertain/initial_point", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_interval_uncertain.initial_point", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_interval_uncertain/interval_probabilities", std::vector<WriteOp>{
      WriteOp{OpKind::DiscreteIntervalUncertain, "discrete_interval_uncertain.basic_probs", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_interval_uncertain/lower_bounds", std::vector<WriteOp>{
      WriteOp{OpKind::DiscreteIntervalUncertain, "discrete_interval_uncertain.basic_probs", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_interval_uncertain/upper_bounds", std::vector<WriteOp>{
      WriteOp{OpKind::DiscreteIntervalUncertain, "discrete_interval_uncertain.basic_probs", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_state_range", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_state_range", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_state_range/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_state_range", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_state_range/descriptors", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_state_range.labels", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_state_range/initial_state", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_state_range.initial_state", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_state_range/lower_bounds", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_state_range.lower_bounds", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_state_range/upper_bounds", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_state_range.upper_bounds", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_state_set/integer", std::vector<WriteOp>{
      WriteOp{OpKind::DiscreteSetValues, "discrete_state_set_int.values", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_state_set/integer/categorical", std::vector<WriteOp>{
      WriteOp{OpKind::Categorical, "discrete_state_set_int.categorical", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_state_set/integer/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_state_set_int", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_state_set/integer/descriptors", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_state_set_int.labels", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_state_set/integer/elements", std::vector<WriteOp>{
      WriteOp{OpKind::DiscreteSetValues, "discrete_state_set_int.values", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_state_set/integer/initial_state", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_state_set_int.initial_state", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_state_set/real", std::vector<WriteOp>{
      WriteOp{OpKind::DiscreteSetValues, "discrete_state_set_real.values", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_state_set/real/categorical", std::vector<WriteOp>{
      WriteOp{OpKind::Categorical, "discrete_state_set_real.categorical", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_state_set/real/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_state_set_real", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_state_set/real/descriptors", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_state_set_real.labels", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_state_set/real/elements", std::vector<WriteOp>{
      WriteOp{OpKind::DiscreteSetValues, "discrete_state_set_real.values", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_state_set/real/initial_state", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_state_set_real.initial_state", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_state_set/string", std::vector<WriteOp>{
      WriteOp{OpKind::DiscreteSetValues, "discrete_state_set_string.values", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_state_set/string/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_state_set_string", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_state_set/string/descriptors", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_state_set_string.labels", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_state_set/string/elements", std::vector<WriteOp>{
      WriteOp{OpKind::DiscreteSetValues, "discrete_state_set_string.values", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_state_set/string/initial_state", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_state_set_string.initial_state", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_uncertain_set/integer", std::vector<WriteOp>{
      WriteOp{OpKind::DiscreteUncertainSetValuesProbs, "discrete_uncertain_set_int.values_probs", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_uncertain_set/integer/categorical", std::vector<WriteOp>{
      WriteOp{OpKind::Categorical, "discrete_uncertain_set_int.categorical", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_uncertain_set/integer/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_uncertain_set_int", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_uncertain_set/integer/initial_point", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_uncertain_set_int.initial_point", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_uncertain_set/integer/set_probabilities", std::vector<WriteOp>{
      WriteOp{OpKind::DiscreteUncertainSetValuesProbs, "discrete_uncertain_set_int.values_probs", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_uncertain_set/real", std::vector<WriteOp>{
      WriteOp{OpKind::DiscreteUncertainSetValuesProbs, "discrete_uncertain_set_real.values_probs", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_uncertain_set/real/categorical", std::vector<WriteOp>{
      WriteOp{OpKind::Categorical, "discrete_uncertain_set_real.categorical", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_uncertain_set/real/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_uncertain_set_real", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_uncertain_set/real/initial_point", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_uncertain_set_real.initial_point", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_uncertain_set/real/set_probabilities", std::vector<WriteOp>{
      WriteOp{OpKind::DiscreteUncertainSetValuesProbs, "discrete_uncertain_set_real.values_probs", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_uncertain_set/string", std::vector<WriteOp>{
      WriteOp{OpKind::DiscreteUncertainSetValuesProbs, "discrete_uncertain_set_string.values_probs", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_uncertain_set/string/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_uncertain_set_string", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_uncertain_set/string/initial_point", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "discrete_uncertain_set_string.initial_point", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("discrete_uncertain_set/string/set_probabilities", std::vector<WriteOp>{
      WriteOp{OpKind::DiscreteUncertainSetValuesProbs, "discrete_uncertain_set_string.values_probs", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("domain/mixed", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceEnum, "domain", OpLiteral{IrValueType::String, IRValue{std::string("MIXED_DOMAIN")}}},
    });
    m.emplace("domain/relaxed", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceEnum, "domain", OpLiteral{IrValueType::String, IRValue{std::string("RELAXED_DOMAIN")}}},
    });
    m.emplace("exponential_uncertain", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "exponential_uncertain", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("exponential_uncertain/betas", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "exponential_uncertain.betas", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("exponential_uncertain/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "exponential_uncertain", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("exponential_uncertain/initial_point", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "exponential_uncertain.initial_point", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("frechet_uncertain", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "frechet_uncertain", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("frechet_uncertain/alphas", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "frechet_uncertain.alphas", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("frechet_uncertain/betas", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "frechet_uncertain.betas", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("frechet_uncertain/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "frechet_uncertain", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("frechet_uncertain/initial_point", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "frechet_uncertain.initial_point", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("gamma_uncertain", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "gamma_uncertain", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("gamma_uncertain/alphas", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "gamma_uncertain.alphas", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("gamma_uncertain/betas", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "gamma_uncertain.betas", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("gamma_uncertain/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "gamma_uncertain", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("gamma_uncertain/initial_point", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "gamma_uncertain.initial_point", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("geometric_uncertain", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "geometric_uncertain", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("geometric_uncertain/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "geometric_uncertain", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("geometric_uncertain/initial_point", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "geometric_uncertain.initial_point", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("geometric_uncertain/probability_per_trial", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "geometric_uncertain.prob_per_trial", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("gumbel_uncertain", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "gumbel_uncertain", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("gumbel_uncertain/alphas", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "gumbel_uncertain.alphas", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("gumbel_uncertain/betas", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "gumbel_uncertain.betas", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("gumbel_uncertain/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "gumbel_uncertain", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("gumbel_uncertain/initial_point", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "gumbel_uncertain.initial_point", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("histogram_bin_uncertain", std::vector<WriteOp>{
      WriteOp{OpKind::HistogramBinUncertain, "histogram_uncertain.bin_pairs", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("histogram_bin_uncertain/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "histogram_uncertain.bin", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("histogram_bin_uncertain/initial_point", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "histogram_bin_uncertain.initial_point", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("histogram_point_uncertain/integer", std::vector<WriteOp>{
      WriteOp{OpKind::HistogramPointUncertain, "histogram_uncertain.point_int_pairs", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("histogram_point_uncertain/integer/abscissas", std::vector<WriteOp>{
      WriteOp{OpKind::HistogramPointUncertain, "histogram_uncertain.point_int_pairs", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("histogram_point_uncertain/integer/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "histogram_uncertain.point_int", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("histogram_point_uncertain/integer/counts", std::vector<WriteOp>{
      WriteOp{OpKind::HistogramPointUncertain, "histogram_uncertain.point_int_pairs", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("histogram_point_uncertain/integer/initial_point", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "histogram_uncertain.point_int.initial_point", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("histogram_point_uncertain/integer/pairs_per_variable", std::vector<WriteOp>{
      WriteOp{OpKind::HistogramPointUncertain, "histogram_uncertain.point_int_pairs", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("histogram_point_uncertain/real", std::vector<WriteOp>{
      WriteOp{OpKind::HistogramPointUncertain, "histogram_uncertain.point_real_pairs", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("histogram_point_uncertain/real/abscissas", std::vector<WriteOp>{
      WriteOp{OpKind::HistogramPointUncertain, "histogram_uncertain.point_real_pairs", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("histogram_point_uncertain/real/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "histogram_uncertain.point_real", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("histogram_point_uncertain/real/counts", std::vector<WriteOp>{
      WriteOp{OpKind::HistogramPointUncertain, "histogram_uncertain.point_real_pairs", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("histogram_point_uncertain/real/initial_point", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "histogram_uncertain.point_real.initial_point", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("histogram_point_uncertain/real/pairs_per_variable", std::vector<WriteOp>{
      WriteOp{OpKind::HistogramPointUncertain, "histogram_uncertain.point_real_pairs", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("histogram_point_uncertain/string", std::vector<WriteOp>{
      WriteOp{OpKind::HistogramPointUncertain, "histogram_uncertain.point_string_pairs", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("histogram_point_uncertain/string/abscissas", std::vector<WriteOp>{
      WriteOp{OpKind::HistogramPointUncertain, "histogram_uncertain.point_string_pairs", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("histogram_point_uncertain/string/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "histogram_uncertain.point_string", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("histogram_point_uncertain/string/counts", std::vector<WriteOp>{
      WriteOp{OpKind::HistogramPointUncertain, "histogram_uncertain.point_string_pairs", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("histogram_point_uncertain/string/initial_point", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "histogram_uncertain.point_string.initial_point", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("histogram_point_uncertain/string/pairs_per_variable", std::vector<WriteOp>{
      WriteOp{OpKind::HistogramPointUncertain, "histogram_uncertain.point_string_pairs", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("hypergeometric_uncertain", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "hypergeometric_uncertain", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("hypergeometric_uncertain/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "hypergeometric_uncertain", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("hypergeometric_uncertain/initial_point", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "hypergeometric_uncertain.initial_point", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("hypergeometric_uncertain/num_drawn", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "hypergeometric_uncertain.num_drawn", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("hypergeometric_uncertain/selected_population", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "hypergeometric_uncertain.selected_population", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("hypergeometric_uncertain/total_population", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "hypergeometric_uncertain.total_population", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("id_variables", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "id", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("linear_equality_constraint_matrix", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "linear_equality_constraints", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("linear_equality_scale_types", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "linear_equality_scale_types", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("linear_equality_scales", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "linear_equality_scales", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("linear_equality_targets", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "linear_equality_targets", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("linear_inequality_constraint_matrix", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "linear_inequality_constraints", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("linear_inequality_lower_bounds", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "linear_inequality_lower_bounds", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("linear_inequality_scale_types", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "linear_inequality_scale_types", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("linear_inequality_scales", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "linear_inequality_scales", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("linear_inequality_upper_bounds", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "linear_inequality_upper_bounds", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("lognormal_uncertain", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "lognormal_uncertain", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("lognormal_uncertain/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "lognormal_uncertain", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("lognormal_uncertain/initial_point", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "lognormal_uncertain.initial_point", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("lognormal_uncertain/lower_bounds", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "lognormal_uncertain.lower_bounds", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("lognormal_uncertain/parameters/option_1/means", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "lognormal_uncertain.means", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("lognormal_uncertain/parameters/option_1/std_deviations", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "lognormal_uncertain.std_deviations", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("lognormal_uncertain/parameters/option_2/error_factors", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "lognormal_uncertain.error_factors", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("lognormal_uncertain/parameters/option_2/means", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "lognormal_uncertain.means", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("lognormal_uncertain/parameters/option_3/lambdas", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "lognormal_uncertain.lambdas", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("lognormal_uncertain/parameters/option_3/zetas", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "lognormal_uncertain.zetas", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("lognormal_uncertain/upper_bounds", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "lognormal_uncertain.upper_bounds", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("loguniform_uncertain", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "loguniform_uncertain", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("loguniform_uncertain/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "loguniform_uncertain", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("loguniform_uncertain/initial_point", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "loguniform_uncertain.initial_point", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("loguniform_uncertain/lower_bounds", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "loguniform_uncertain.lower_bounds", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("loguniform_uncertain/upper_bounds", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "loguniform_uncertain.upper_bounds", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("negative_binomial_uncertain", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "negative_binomial_uncertain", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("negative_binomial_uncertain/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "negative_binomial_uncertain", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("negative_binomial_uncertain/initial_point", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "negative_binomial_uncertain.initial_point", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("negative_binomial_uncertain/num_trials", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "negative_binomial_uncertain.num_trials", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("negative_binomial_uncertain/probability_per_trial", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "negative_binomial_uncertain.prob_per_trial", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("normal_uncertain", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "normal_uncertain", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("normal_uncertain/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "normal_uncertain", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("normal_uncertain/initial_point", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "normal_uncertain.initial_point", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("normal_uncertain/lower_bounds", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "normal_uncertain.lower_bounds", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("normal_uncertain/means", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "normal_uncertain.means", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("normal_uncertain/std_deviations", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "normal_uncertain.std_deviations", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("normal_uncertain/upper_bounds", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "normal_uncertain.upper_bounds", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("poisson_uncertain", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "poisson_uncertain", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("poisson_uncertain/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "poisson_uncertain", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("poisson_uncertain/initial_point", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "poisson_uncertain.initial_point", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("poisson_uncertain/lambdas", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "poisson_uncertain.lambdas", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("triangular_uncertain", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "triangular_uncertain", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("triangular_uncertain/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "triangular_uncertain", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("triangular_uncertain/initial_point", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "triangular_uncertain.initial_point", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("triangular_uncertain/lower_bounds", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "triangular_uncertain.lower_bounds", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("triangular_uncertain/modes", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "triangular_uncertain.modes", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("triangular_uncertain/upper_bounds", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "triangular_uncertain.upper_bounds", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("uncertain_correlation_matrix", std::vector<WriteOp>{
      WriteOp{OpKind::UncertainCorrelationMatrix, "uncertain.correlation_matrix", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("uniform_uncertain", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "uniform_uncertain", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("uniform_uncertain/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "uniform_uncertain", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("uniform_uncertain/initial_point", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "uniform_uncertain.initial_point", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("uniform_uncertain/lower_bounds", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "uniform_uncertain.lower_bounds", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("uniform_uncertain/upper_bounds", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "uniform_uncertain.upper_bounds", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("weibull_uncertain", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "weibull_uncertain", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("weibull_uncertain/alphas", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "weibull_uncertain.alphas", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("weibull_uncertain/betas", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "weibull_uncertain.betas", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("weibull_uncertain/count", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "weibull_uncertain", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("weibull_uncertain/initial_point", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "weibull_uncertain.initial_point", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    return m;
  }();
  return kInstructions;
}

} // namespace dakota::irgen::variables
