// Auto-generated by update_pdb_keys/generate_ir_tables.py
// type-signature: c42d47e99d2e6743f33c63846b24407d541c6c30efed719d849d9a7bc18d0e77
#pragma once

#include <string>
#include <unordered_map>
#include <variant>
#include <vector>
#include <nlohmann/json.hpp>
#include "dakota_data_types.hpp"

namespace dakota::irgen {

enum class IrValueType {
  UnspecifiedType,
  BitArray,
  IntIntPairRealMapArray,
  IntRealMapArray,
  IntSet,
  IntSetArray,
  IntVector,
  Real,
  RealMatrixArray,
  RealRealMapArray,
  RealRealPairRealMapArray,
  RealSetArray,
  RealSymMatrix,
  RealVector,
  RealVectorArray,
  SizetArray,
  SizetSet,
  String,
  String2DArray,
  StringArray,
  StringRealMapArray,
  StringSetArray,
  UShortArray,
  Bool,
  Int,
  Short,
  SizeT,
  UnsignedShort,
};

enum class OpKind {
  AdjacencyMatrix,
  AugmentEnum,
  Categorical,
  ContinuousIntervalUncertain,
  DirectValue,
  DiscreteIntervalUncertain,
  DiscreteSetValues,
  DiscreteUncertainSetValuesProbs,
  HistogramBinUncertain,
  HistogramPointUncertain,
  IdToIndexSet,
  IntSet,
  LiteralAssign,
  PresenceBool,
  PresenceEnum,
  PresenceLiteral,
  UncertainCorrelationMatrix,
};

using IRValue = std::variant<std::monostate, Dakota::BitArray, Dakota::IntIntPairRealMapArray, Dakota::IntRealMapArray, Dakota::IntSet, Dakota::IntSetArray, Dakota::IntVector, Dakota::Real, Dakota::RealMatrixArray, Dakota::RealRealMapArray, Dakota::RealRealPairRealMapArray, Dakota::RealSetArray, Dakota::RealSymMatrix, Dakota::RealVector, Dakota::RealVectorArray, Dakota::SizetArray, Dakota::SizetSet, Dakota::String, Dakota::String2DArray, Dakota::StringArray, Dakota::StringRealMapArray, Dakota::StringSetArray, Dakota::UShortArray, bool, int, short, size_t, unsigned short, nlohmann::json>;

} // namespace dakota::irgen
