// Auto-generated by update_pdb_keys/generate_ir_tables.py
#include "generated_ir_table_types.hpp"

namespace dakota::irgen {

const BlockTables& tables_for_block(BlockType block) {
  switch (block) {
    case BlockType::Environment: {
      static const BlockTables t{environment::contracts(), environment::instructions()};
      return t;
    }
    case BlockType::Method: {
      static const BlockTables t{method::contracts(), method::instructions()};
      return t;
    }
    case BlockType::Model: {
      static const BlockTables t{model::contracts(), model::instructions()};
      return t;
    }
    case BlockType::Variables: {
      static const BlockTables t{variables::contracts(), variables::instructions()};
      return t;
    }
    case BlockType::Interface: {
      static const BlockTables t{interface::contracts(), interface::instructions()};
      return t;
    }
    case BlockType::Responses: {
      static const BlockTables t{responses::contracts(), responses::instructions()};
      return t;
    }
  }
  static const BlockTables fallback{environment::contracts(), environment::instructions()};
  return fallback;
}

} // namespace dakota::irgen
