// Auto-generated by update_pdb_keys/generate_ir_tables.py
// Block: environment
#include "generated_ir_table_types.hpp"

namespace dakota::irgen::environment {

const std::unordered_map<std::string, KeyContract>& contracts() {
  static const auto kContracts = []() {
    std::unordered_map<std::string, KeyContract> m;
    m.reserve(28);
    m.emplace("check", KeyContract{IrValueType::Bool, DefaultSource::Policy, IRValue{bool(false)}});
    m.emplace("error_file", KeyContract{IrValueType::String, DefaultSource::Policy, IRValue{std::string("")}});
    m.emplace("graphics", KeyContract{IrValueType::Bool, DefaultSource::Policy, IRValue{bool(false)}});
    m.emplace("interface_evals_selection", KeyContract{IrValueType::UnsignedShort, DefaultSource::Schema, IRValue{std::string("INTERF_EVAL_STORE_SIMULATION")}});
    m.emplace("model_evals_selection", KeyContract{IrValueType::UnsignedShort, DefaultSource::Schema, IRValue{std::string("MODEL_EVAL_STORE_TOP_METHOD")}});
    m.emplace("output_file", KeyContract{IrValueType::String, DefaultSource::Policy, IRValue{std::string("")}});
    m.emplace("output_precision", KeyContract{IrValueType::Int, DefaultSource::Schema, IRValue{int(0)}});
    m.emplace("post_run", KeyContract{IrValueType::Bool, DefaultSource::Policy, IRValue{bool(false)}});
    m.emplace("post_run_input", KeyContract{IrValueType::String, DefaultSource::Policy, IRValue{std::string("")}});
    m.emplace("post_run_input_format", KeyContract{IrValueType::UnsignedShort, DefaultSource::Schema, IRValue{std::string("TABULAR_ANNOTATED")}});
    m.emplace("post_run_output", KeyContract{IrValueType::String, DefaultSource::Policy, IRValue{std::string("")}});
    m.emplace("pre_run", KeyContract{IrValueType::Bool, DefaultSource::Policy, IRValue{bool(false)}});
    m.emplace("pre_run_input", KeyContract{IrValueType::String, DefaultSource::Policy, IRValue{std::string("")}});
    m.emplace("pre_run_output", KeyContract{IrValueType::String, DefaultSource::Policy, IRValue{std::string("")}});
    m.emplace("pre_run_output_format", KeyContract{IrValueType::UnsignedShort, DefaultSource::Schema, IRValue{std::string("TABULAR_ANNOTATED")}});
    m.emplace("read_restart", KeyContract{IrValueType::String, DefaultSource::Policy, IRValue{std::string("")}});
    m.emplace("results_output", KeyContract{IrValueType::Bool, DefaultSource::Policy, IRValue{bool(false)}});
    m.emplace("results_output_file", KeyContract{IrValueType::String, DefaultSource::Schema, IRValue{std::string("dakota_results")}});
    m.emplace("results_output_format", KeyContract{IrValueType::UnsignedShort, DefaultSource::Policy, IRValue{static_cast<unsigned short>(0)}});
    m.emplace("run", KeyContract{IrValueType::Bool, DefaultSource::Policy, IRValue{bool(false)}});
    m.emplace("run_input", KeyContract{IrValueType::String, DefaultSource::Policy, IRValue{std::string("")}});
    m.emplace("run_output", KeyContract{IrValueType::String, DefaultSource::Policy, IRValue{std::string("")}});
    m.emplace("stop_restart", KeyContract{IrValueType::Int, DefaultSource::Policy, IRValue{int(0)}});
    m.emplace("tabular_format", KeyContract{IrValueType::UnsignedShort, DefaultSource::Schema, IRValue{std::string("TABULAR_ANNOTATED")}});
    m.emplace("tabular_graphics_data", KeyContract{IrValueType::Bool, DefaultSource::Policy, IRValue{bool(false)}});
    m.emplace("tabular_graphics_file", KeyContract{IrValueType::String, DefaultSource::Schema, IRValue{std::string("dakota_tabular.dat")}});
    m.emplace("top_method_pointer", KeyContract{IrValueType::String, DefaultSource::Policy, IRValue{std::string("")}});
    m.emplace("write_restart", KeyContract{IrValueType::String, DefaultSource::Policy, IRValue{std::string("")}});
    return m;
  }();
  return kContracts;
}

const std::unordered_map<std::string, std::vector<WriteOp>>& instructions() {
  static const auto kInstructions = []() {
    std::unordered_map<std::string, std::vector<WriteOp>> m;
    m.reserve(52);
    m.emplace("check", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceBool, "check", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("error_file", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "error_file", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("graphics", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceBool, "graphics", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("output_file", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "output_file", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("output_precision", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "output_precision", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("post_run", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceBool, "post_run", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("post_run/input", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "post_run_input", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("post_run/input/filename", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "post_run_input", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("post_run/input/format/annotated", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceEnum, "post_run_input_format", OpLiteral{IrValueType::String, IRValue{std::string("TABULAR_ANNOTATED")}}},
    });
    m.emplace("post_run/input/format/custom_annotated", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceEnum, "post_run_input_format", OpLiteral{IrValueType::String, IRValue{std::string("TABULAR_NONE")}}},
    });
    m.emplace("post_run/input/format/custom_annotated/eval_id", std::vector<WriteOp>{
      WriteOp{OpKind::AugmentEnum, "post_run_input_format", OpLiteral{IrValueType::String, IRValue{std::string("TABULAR_EVAL_ID")}}},
    });
    m.emplace("post_run/input/format/custom_annotated/header", std::vector<WriteOp>{
      WriteOp{OpKind::AugmentEnum, "post_run_input_format", OpLiteral{IrValueType::String, IRValue{std::string("TABULAR_HEADER")}}},
    });
    m.emplace("post_run/input/format/custom_annotated/interface_id", std::vector<WriteOp>{
      WriteOp{OpKind::AugmentEnum, "post_run_input_format", OpLiteral{IrValueType::String, IRValue{std::string("TABULAR_IFACE_ID")}}},
    });
    m.emplace("post_run/input/format/freeform", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceEnum, "post_run_input_format", OpLiteral{IrValueType::String, IRValue{std::string("TABULAR_NONE")}}},
    });
    m.emplace("post_run/output", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "post_run_output", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("pre_run", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceBool, "pre_run", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("pre_run/input", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "pre_run_input", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("pre_run/output", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "pre_run_output", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("pre_run/output/filename", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "pre_run_output", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("pre_run/output/format/annotated", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceEnum, "pre_run_output_format", OpLiteral{IrValueType::String, IRValue{std::string("TABULAR_ANNOTATED")}}},
    });
    m.emplace("pre_run/output/format/custom_annotated", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceEnum, "pre_run_output_format", OpLiteral{IrValueType::String, IRValue{std::string("TABULAR_NONE")}}},
    });
    m.emplace("pre_run/output/format/custom_annotated/eval_id", std::vector<WriteOp>{
      WriteOp{OpKind::AugmentEnum, "pre_run_output_format", OpLiteral{IrValueType::String, IRValue{std::string("TABULAR_EVAL_ID")}}},
    });
    m.emplace("pre_run/output/format/custom_annotated/header", std::vector<WriteOp>{
      WriteOp{OpKind::AugmentEnum, "pre_run_output_format", OpLiteral{IrValueType::String, IRValue{std::string("TABULAR_HEADER")}}},
    });
    m.emplace("pre_run/output/format/custom_annotated/interface_id", std::vector<WriteOp>{
      WriteOp{OpKind::AugmentEnum, "pre_run_output_format", OpLiteral{IrValueType::String, IRValue{std::string("TABULAR_IFACE_ID")}}},
    });
    m.emplace("pre_run/output/format/freeform", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceEnum, "pre_run_output_format", OpLiteral{IrValueType::String, IRValue{std::string("TABULAR_NONE")}}},
    });
    m.emplace("read_restart", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "read_restart", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("read_restart/filename", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "read_restart", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("read_restart/stop_restart", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "stop_restart", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("results_output", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceBool, "results_output", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("results_output/hdf5", std::vector<WriteOp>{
      WriteOp{OpKind::AugmentEnum, "results_output_format", OpLiteral{IrValueType::String, IRValue{std::string("RESULTS_OUTPUT_HDF5")}}},
    });
    m.emplace("results_output/hdf5/interface_selection/all", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceEnum, "interface_evals_selection", OpLiteral{IrValueType::String, IRValue{std::string("INTERF_EVAL_STORE_ALL")}}},
    });
    m.emplace("results_output/hdf5/interface_selection/none", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceEnum, "interface_evals_selection", OpLiteral{IrValueType::String, IRValue{std::string("INTERF_EVAL_STORE_NONE")}}},
    });
    m.emplace("results_output/hdf5/interface_selection/simulation", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceEnum, "interface_evals_selection", OpLiteral{IrValueType::String, IRValue{std::string("INTERF_EVAL_STORE_SIMULATION")}}},
    });
    m.emplace("results_output/hdf5/model_selection/all", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceEnum, "model_evals_selection", OpLiteral{IrValueType::String, IRValue{std::string("MODEL_EVAL_STORE_ALL")}}},
    });
    m.emplace("results_output/hdf5/model_selection/all_methods", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceEnum, "model_evals_selection", OpLiteral{IrValueType::String, IRValue{std::string("MODEL_EVAL_STORE_ALL_METHODS")}}},
    });
    m.emplace("results_output/hdf5/model_selection/none", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceEnum, "model_evals_selection", OpLiteral{IrValueType::String, IRValue{std::string("MODEL_EVAL_STORE_NONE")}}},
    });
    m.emplace("results_output/hdf5/model_selection/top_method", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceEnum, "model_evals_selection", OpLiteral{IrValueType::String, IRValue{std::string("MODEL_EVAL_STORE_TOP_METHOD")}}},
    });
    m.emplace("results_output/results_output_file", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "results_output_file", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("results_output/text", std::vector<WriteOp>{
      WriteOp{OpKind::AugmentEnum, "results_output_format", OpLiteral{IrValueType::String, IRValue{std::string("RESULTS_OUTPUT_TEXT")}}},
    });
    m.emplace("run", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceBool, "run", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("run/input", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "run_input", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("run/output", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "run_output", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("tabular_data", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceBool, "tabular_graphics_data", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("tabular_data/format/annotated", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceEnum, "tabular_format", OpLiteral{IrValueType::String, IRValue{std::string("TABULAR_ANNOTATED")}}},
    });
    m.emplace("tabular_data/format/custom_annotated", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceEnum, "tabular_format", OpLiteral{IrValueType::String, IRValue{std::string("TABULAR_NONE")}}},
    });
    m.emplace("tabular_data/format/custom_annotated/eval_id", std::vector<WriteOp>{
      WriteOp{OpKind::AugmentEnum, "tabular_format", OpLiteral{IrValueType::String, IRValue{std::string("TABULAR_EVAL_ID")}}},
    });
    m.emplace("tabular_data/format/custom_annotated/header", std::vector<WriteOp>{
      WriteOp{OpKind::AugmentEnum, "tabular_format", OpLiteral{IrValueType::String, IRValue{std::string("TABULAR_HEADER")}}},
    });
    m.emplace("tabular_data/format/custom_annotated/interface_id", std::vector<WriteOp>{
      WriteOp{OpKind::AugmentEnum, "tabular_format", OpLiteral{IrValueType::String, IRValue{std::string("TABULAR_IFACE_ID")}}},
    });
    m.emplace("tabular_data/format/freeform", std::vector<WriteOp>{
      WriteOp{OpKind::PresenceEnum, "tabular_format", OpLiteral{IrValueType::String, IRValue{std::string("TABULAR_NONE")}}},
    });
    m.emplace("tabular_data/tabular_data_file", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "tabular_graphics_file", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("top_method_pointer", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "top_method_pointer", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    m.emplace("write_restart", std::vector<WriteOp>{
      WriteOp{OpKind::DirectValue, "write_restart", OpLiteral{IrValueType::UnspecifiedType, IRValue{std::monostate{}}}},
    });
    return m;
  }();
  return kInstructions;
}

} // namespace dakota::irgen::environment
