// Auto-generated by update_pdb_keys/generate_ir_tables.py
// type-signature: 432e6a58e3fe6bacdfc8deeb8748e0a9a03ce030335c126bc056037d4245c077
#pragma once

#include <string>
#include <unordered_map>
#include <variant>
#include <vector>
#include <nlohmann/json.hpp>
#include "dakota_data_types.hpp"

namespace dakota::irgen {

enum class IrValueType {
  UnspecifiedType,
  BitArray,
  IntIntPairRealMapArray,
  IntRealMapArray,
  IntSet,
  IntSetArray,
  IntVector,
  Real,
  RealMatrixArray,
  RealRealMapArray,
  RealRealPairRealMapArray,
  RealSetArray,
  RealSymMatrix,
  RealVector,
  RealVectorArray,
  SizetArray,
  SizetSet,
  String,
  String2DArray,
  StringArray,
  StringRealMapArray,
  StringSetArray,
  UShortArray,
  Bool,
  Int,
  Short,
  SizeT,
  UnsignedShort,
};

enum class OpKind {
  AugmentEnum,
  Categorical,
  ContinuousIntervalUncertain,
  DirectValue,
  DiscreteIntervalUncertain,
  DiscreteUncertainSetValuesProbs,
  HistogramBinUncertain,
  HistogramPointUncertain,
  LiteralAssign,
  PresenceBool,
  PresenceEnum,
  PresenceLiteral,
  TypeData,
  UncertainCorrelationMatrix,
};

using IRValue = std::variant<std::monostate, Dakota::BitArray, Dakota::IntIntPairRealMapArray, Dakota::IntRealMapArray, Dakota::IntSet, Dakota::IntSetArray, Dakota::IntVector, Dakota::Real, Dakota::RealMatrixArray, Dakota::RealRealMapArray, Dakota::RealRealPairRealMapArray, Dakota::RealSetArray, Dakota::RealSymMatrix, Dakota::RealVector, Dakota::RealVectorArray, Dakota::SizetArray, Dakota::SizetSet, Dakota::String, Dakota::String2DArray, Dakota::StringArray, Dakota::StringRealMapArray, Dakota::StringSetArray, Dakota::UShortArray, bool, int, short, size_t, unsigned short, nlohmann::json>;

} // namespace dakota::irgen
