/* Generated by wbuild from "RowCol.w"
** (generator version $Revision: 404 $ of $Date: 1999-09-28 09:56:30 -0600 (Tue, 28 Sep 1999) $)
*/
#ifndef _XfwfRowCol_H_
#define _XfwfRowCol_H_
#include "Board.h"
_XFUNCPROTOBEGIN
#ifndef XtNstoreByRow
#define XtNstoreByRow "storeByRow"
#endif
#ifndef XtCStoreByRow
#define XtCStoreByRow "StoreByRow"
#endif
#ifndef XtRBoolean
#define XtRBoolean "Boolean"
#endif

#ifndef XtNrows
#define XtNrows "rows"
#endif
#ifndef XtCRows
#define XtCRows "Rows"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNcolumns
#define XtNcolumns "columns"
#endif
#ifndef XtCColumns
#define XtCColumns "Columns"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNalignment
#define XtNalignment "alignment"
#endif
#ifndef XtCAlignment
#define XtCAlignment "Alignment"
#endif
#ifndef XtRAlignment
#define XtRAlignment "Alignment"
#endif

#ifndef XtNshrinkToFit
#define XtNshrinkToFit "shrinkToFit"
#endif
#ifndef XtCShrinkToFit
#define XtCShrinkToFit "ShrinkToFit"
#endif
#ifndef XtRBoolean
#define XtRBoolean "Boolean"
#endif

typedef struct _XfwfRowColClassRec *XfwfRowColWidgetClass;
typedef struct _XfwfRowColRec *XfwfRowColWidget;
externalref WidgetClass xfwfRowColWidgetClass;
_XFUNCPROTOEND
#endif /*_XfwfRowCol_H_*/
