/* XPM */
static char * wheel3 [] = {
/* width height ncolors cpp [x_hot y_hot] */
"15 64 10 1 0 0",
/* colors */
" 	s iconColor1	m black	c black",
".	s iconColor6	m white	c yellow",
"X	s iconGray8	m black	c #323232323232",
"o	s iconGray1	m white	c #e1e1e1e1e1e1",
"O	s iconColor2	m white	c white",
"+	s iconGray6	m black	c #646464646464",
"@	s iconGray2	m white	c #c8c8c8c8c8c8",
"#	s iconGray3	m white	c #afafafafafaf",
"$	s iconGray4	m white	c #969696969696",
"%	s iconGray5	m black	c #7d7d7d7d7d7d",
/* pixels */
"               ",
"       .       ",
"XXXXXX...XXXXXX",
"XXXXX.....XXXXX",
"XXXX.......XXXX",
"XXX.........XXX",
"XX...........XX",
"X.............X",
"X              ",
"XoooooooooooooX",
"XOOOOOOOOOOOOOX",
"X+++++++++++++X",
"XoooooooooooooX",
"XoooooooooooooX",
"XoooooooooooooX",
"X@o@o@o@o@o@o@X",
"XoooooooooooooX",
"Xo@o@o@o@o@o@oX",
"XOOOOOOOOOOOOOX",
"X+++++++++++++X",
"Xo@o@o@o@o@o@oX",
"X@@@@@@@@@@@@@ ",
"X@@@@@@@@@@@@@X",
"X@@@@@@@@@@@@@X",
" @#@#@#@#@#@#@X",
" #@#@#@#@#@#@#X",
" #############X",
" @#@#@#@#@#@#@X",
"X#############X",
"XOOOOOOOOOOOOOX",
"X             X",
" #############X",
"X#############X",
"X#############X",
"X#$#$#$#$#$#$#X",
"X$#$#$#$#$#$#$X",
" $$$$$$$$$$$$$X",
"X#$#$#$#$#$#$#X",
"X$$$$$$$$$$$$$X",
"X$$$$$$$$$$$$$X",
"X$$$$$$$$$$$$$X",
" oooooooooooooX",
"X             X",
"X$$$$$$$$$$$$$X",
"X%%%%%%%%%%%%%X",
"X%%%%%%%%%%%%%X",
" %%%%%%%%%%%%%X",
"X+%+%+%+%+%+%+X",
"XoooooooooooooX",
"X             X",
"X+++++++++++++X",
" +++++++++++++X",
"X+++++++++++++X",
"X+++++++++++++X",
"X+++++++++++++X",
"X+++++++++++++X",
"X.............X",
"XX...........XX",
"XXX.........XXX",
"XXXX.......XXXX",
"XXXXX.....XXXXX",
"XXXXXX...XXXXXX",
"       .       ",
"               "};
